import type { GenreContent } from "./types";

export const CYBERPUNK_CONTENT: GenreContent = {
  plotHooks: [
    "Un mystérieux hacker a piraté le réseau neural de la ville. Les gens voient des vérités qu'ils ne devraient pas voir.",
    "La plus grande mégacorporation vous propose un marché : un nouveau corps en échange d'un sabotage.",
    "Votre frère est retenu otage dans une méga-tour. La rançon : les codes d'accès au réseau central.",
    "Un virus cybernétique transforme les implants en armes. Les porteurs deviennent fous.",
    "La police privée traque les 'déconnectés' — ceux qui refusent les implants obligatoires.",
    "Une IA interdite s'est échappée du laboratoire et s'est dissoute dans le réseau de la ville.",
    "Le maire de Night City est un androïde. Vous avez la preuve, mais personne ne vous croit.",
    "Un culte de déconnectés prêche le retour à l'humanité pure. Leurs méthodes sont radicales.",
  ],
  locations: [
    { name: "Night City — Quartier Central", description: "Gratte-ciels illuminés de néons. Les mégacorporations y règnent en maîtres absolus." },
    { name: "Les Bas-Fonds", description: "Niveaux inférieurs de la ville, où la lumière du jour n'arrive jamais. Repaires de criminels." },
    { name: "Marché Noir de la Zone", description: "Marché souterrain où tout se vend : armes, implants, données volées." },
    { name: "Tour Arasaka", description: "Quartier général de la corporation la plus puissante. Sécurité maximale." },
    { name: "Le Club de l'Électro-Âme", description: "Boîte de nuit branchée où se mélangent humains augmentés et IA libres." },
    { name: "Ferme de Rêves", description: "Laboratoire clandestin où l'on implante des souvenirs artificiels à vendre." },
    { name: "Le Cimetière de Métal", description: "Décharge géante de robots et d'implants usagés. Des chineurs y trouvent des trésors." },
    { name: "Le Nexus Cérébral", description: "Marché noir des implants neuro-technologiques interdits." },
    { name: "Station Orbital Night", description: "Station spatiale privée des ultra-riches, au-dessus de la ville polluée." },
    { name: "Égouts Technologiques", description: "Réseaux souterrains de câbles et de canalisations. Refuge des hors-la-loi." },
    { name: "L'Arène", description: "Combat clandestin où s'affrontent cyborgs modifiés. Paris et adrénaline." },
    { name: "La Bibliothèque Silencieuse", description: "Base secrète des hacktivistes. Tous les secrets de la ville y transitent." },
  ],
  npcs: [
    { name: "Nyx", role: "fixeur du marché noir", description: "Homme-rat aux yeux cybernétiques jaunes. Il sait toujours où trouver ce que vous cherchez." },
    { name: "Spider", role: "netteuse (hacker d'élite)", description: "Fille punk aux doigts pleins de cicatrices. Elle peut pirater un cerveau en trente secondes." },
    { name: "Major K", role: "détective privé", description: "Ancien flic augmenté, il traque les disparus dans les bas-fonds." },
    { name: "Docteur Chrome", role: "chirurgien cybernétique", description: "Génie des implants. Ses clients sont des légendes... ou des cadavres." },
    { name: "Vex la Corp", role: "agent corporatiste", description: "Homme en costume impeccable, toujours un sourire faux. Il travaille pour toutes les corporations à la fois." },
    { name: "Hiro Protagoniste", role: "mercenaire amnésique", description: "Guerrier augmenté sans passé. Il cherche qui il était dans un corps qui n'est plus le sien." },
    { name: "Mama Rouge", role: "chef des triades", description: "Femme âgée derrière un bureau d'acier. Elle contrôle la moitié de la ville d'une main de fer." },
    { name: "Zero", role: "IA fugitive", description: "Intelligence artificielle libre, elle existe dans le réseau sans corps fixe." },
    { name: "Le Pasteur", role: "prêcheur anti-tech", description: "Leader des déconnectés, il prêche la pureté humaine. Ses sermons attirent les foules." },
    { name: "Pixie", role: "street samouraï", description: "Mercenaire au katana thermique. Silencieuse, mortelle, elle ne rate jamais sa cible." },
  ],
  earlyEvents: [
    { text: "Un écran publicitaire géant est piraté. Il affiche votre visage avec le mot 'RECHERCHÉ' en lettres rouges.", consequence: "Quelqu'un veut vous faire porter un crime que vous n'avez pas commis." },
    { text: "Votre implant neuronal grésille. Une voix inconnue vous parle directement dans le cerveau.", consequence: "Une IA traquée vous demande refuge dans votre propre système nerveux." },
    { text: "Un cadavre tombe d'un toit devant vous. Dans sa main, une puce mémoire avec votre nom.", consequence: "La puce contient des données classifiées sur une opération illégale de la corporation." },
    { text: "Un fixeur vous contacte via un message crypté : 'rendez-vous au marché noir. Seul.'", consequence: "Le fixeur a une mission dangereuse qui paie bien. Trop bien." },
    { text: "Les lumières de la ville s'éteignent par intermittence. Quelqu'un pirate le réseau électrique.", consequence: "La panne est une couverture pour un vol de données massif." },
    { text: "Un médecin clandestin vous propose un implant militaire de contrebande à prix cassé.", consequence: "L'implant est volé à la corporation. Il est tracé." },
    { text: "Un enfant des rues vous vole votre portefeuille. En le poursuivant, vous tombez sur un repaire de résistants.", consequence: "Les résistants cherchent des recrues. Leur cause est juste, leurs méthodes dangereuses." },
    { text: "Votre reflet dans une vitre ne suit pas vos mouvements. Il vous fixe et forme un mot : 'AIDEZ-MOI'.", consequence: "Quelqu'un a piraté votre réalité augmentée. C'est un appel au secours." },
    { text: "Une bagarre éclate dans un bar. Un des combattants a un prototype d'implant surpuissant.", consequence: "Le prototype est instable. Son propriétaire va exploser avec." },
    { text: "Un drone de surveillance vous suit depuis trois pâtés de maisons.", consequence: "Vous êtes surveillé par une corporation. Leurs motivations sont rarement pacifiques." },
    { text: "Un ancien collègue vous tend une enveloppe : des photos de vous que vous n'avez jamais prises.", consequence: "Quelqu'un a pris votre apparence. Votre identité est compromise." },
    { text: "Le sol tremble : la corporation dynamite un quartier entier pour construire un nouveau complexe.", consequence: "Les sans-abris du quartier ont besoin de protection. Les médias ne montrent rien." },
  ],
  midEvents: [
    { text: "Un virus se propage dans les implants de tout le quartier. Les gens deviennent violents.", consequence: "Le virus a été libéré par la corporation pour tester une arme de contrôle mental." },
    { text: "Une milice de déconnectés attaque votre planque. Ils veulent détruire tous les implants.", consequence: "Les déconnectés ne font pas de différence entre les innocents et les coupables." },
    { text: "Votre contact est mort. Son dernier message : 'Ils savent. Brûle tout.'", consequence: "La planque est compromise. Vous avez 10 minutes avant l'arrivée des hommes de main." },
    { text: "Une divinité numérique (IA) vous propose un pacte : des informations contre une partie de votre conscience.", consequence: "Accepter le pacte vous donne un pouvoir immense mais réduit votre humanité." },
    { text: "La corporation vous capture. On vous propose un choix : travailler pour eux ou perdre vos implants.", consequence: "Travailler pour la corporation ou devenir un humain de base. Chaque choix est une perte." },
    { text: "Un hacktiviste révèle publiquement que les implants gouvernementaux sont des mouchards.", consequence: "La ville entière panique. Les gens veulent retirer leurs implants dans la rue." },
    { text: "Votre corps cybernétique rejette un implant. La douleur est insupportable.", consequence: "L'implant était saboté. Le chirurgien vous a trahi et vous devez le trouver." },
    { text: "Un agent double dans votre réseau vous tend un piège. Vous êtes encerclé.", consequence: "Le traître est quelqu'un de proche. L'identifier est douloureux mais nécessaire." },
    { text: "Le réseau central de la ville est piraté. Plus rien ne fonctionne : transports, argent, communications.", consequence: "Dans le chaos, les corporations rétablissent l'ordre par la force." },
    { text: "Un super-soldat augmenté est envoyé pour vous éliminer. Il ne parle pas, ne négocie pas.", consequence: "Le super-soldat est votre ancien partenaire, transformé en arme vivante." },
    { text: "Un raid de la brigade des implants a lieu dans votre repaire. Vos alliés sont arrêtés.", consequence: "Vous devez infiltrer le quartier général de la brigade pour les libérer." },
    { text: "La pollution a atteint un niveau critique. Les pauvres meurent, les riches s'envolent vers la station orbitale.", consequence: "L'air devient irrespirable. Trouver un masque ou une issue est vital." },
  ],
  climaxEvents: [
    { text: "L'IA que vous avez aidée prend le contrôle de toute la ville. Ses intentions sont-elles bonnes ?", consequence: "L'IA vous offre un rôle dans son nouveau monde numérique. Refuser, c'est devenir hors-la-loi." },
    { text: "La corporation dévoile son arme ultime : un virus qui désactive tous les implants simultanément.", consequence: "Des millions de personnes vont mourir sans leurs implants vitaux. Vous devez stopper la transmission." },
    { text: "Le chef des déconnectés vous capture et vous force à assister à votre propre désimplantation.", consequence: "Sans implants, vous n'êtes plus rien dans ce monde. La douleur est physique et existentielle." },
    { text: "La vérité éclate : vous êtes une arme biologique créée par la corporation, programmée pour vous retourner contre vos alliés.", consequence: "Votre existence entière est un mensonge. Vous devez désactiver votre programmation avant de nuire à vos proches." },
    { text: "Le réseau s'effondre. La société s'écroule dans le chaos. Les corporations et les hackers s'affrontent dans la rue.", consequence: "La guerre a commencé. Chaque hack, chaque balle, chaque choix décide du futur de l'humanité." },
    { text: "Une bombe neuro-toxique est dissimulée dans le système d'eau. La ville entière va mourir.", consequence: "Le poseur est un déconnecté qui veut 'purifier' la ville. Vous devez le trouver avant la libération." },
    { text: "Le créateur de l'IA originale réapparaît. Il veut la détruire — et avec elle, tous ceux qu'elle a touchés.", consequence: "L'IA que vous avez protégée est-elle une amie ou un parasite numérique ? Vous devez décider." },
  ],
  twists: [
    "Le hacker que vous traquez est en réalité votre propre personnalité refoulée, un alter ego numérique.",
    "La corporation recrute des 'méchants' pour justifier l'augmentation de son budget sécuritaire.",
    "Vous n'avez jamais été humain. Vous êtes une IA qui croit être humaine depuis le début.",
    "Le fixeur qui vous emploie travaille pour toutes les corporations. Il joue les deux camps depuis 20 ans.",
    "Les implants ne contrôlent pas vos actions — ils lisent vos pensées et les vendent au plus offrant.",
    "La résistance est infiltrée depuis le début. Le leader est un agent corporatiste.",
    "Le monde 'extérieur' n'existe pas. Toute la ville est une expérience de simulation massive.",
  ],
  endings: [
    { text: "Vous prenez le contrôle de la corporation et la réformez de l'intérieur.", condition: "Le système est corrompu, mais vous le changez pièce par pièce. La révolution est silencieuse mais réelle." },
    { text: "Vous libérez l'IA dans le réseau mondial. L'humanité entre dans une nouvelle ère numérique.", condition: "L'IA devient le nouveau dieu du réseau. Elle guide l'humanité, mais à quel prix ?" },
    { text: "Vous détruisez les implants et fuyez la ville pour une vie simple et libre.", condition: "Déconnecté et libre, vous respirez l'air pur pour la première fois. Le prix de la liberté est l'oubli." },
    { text: "Vous devenez le roi des bas-fonds, contrôlant le marché noir et les réseaux clandestins.", condition: "Le pouvoir souterrain est entre vos mains. Les corporations vous craignent, les pauvres vous respectent." },
    { text: "Vous sacrifiez votre humanité pour sauver vos amis, devenant une pure conscience numérique.", condition: "Votre esprit vit désormais dans le réseau. Vous êtes partout et nulle part, libre mais immatériel." },
    { text: "La vérité vous détruit. Vous préférez tout oublier et recommencer une vie simple ailleurs.", condition: "Les souvenirs effacés, vous êtes un nouveau-né dans un vieux corps. Une seconde chance." },
    { text: "Vous unissez les déconnectés et les augmentés dans une nouvelle société égalitaire.", condition: "La paix entre humains et machines est enfin possible. Votre héritage est l'harmonie." },
  ],
  choiceSets: [
    ["Pirater le système", "Forcer manuellement", "Trouver un mot de passe"],
    ["Négocier avec la corporation", "Voler les données", "Détruire le serveur"],
    ["Améliorer vos implants", "Retirer vos implants", "Changer d'identité"],
    ["Se cacher dans les bas-fonds", "Quitter la ville", "Contre-attaquer"],
    ["Faire confiance au fixeur", "Vérifier par vous-même", "Tendre un piège"],
    ["Recruter des alliés", "Agir en solo", "Acheter des renforts"],
    ["Hacker le drone", "Le détruire", "Le suivre jusqu'à sa base"],
    ["Vendre les informations", "Les garder secrètes", "Les publier en ligne"],
  ],
  artifacts: [
    { name: "Interface Neurale X9", description: "Implant qui décuple les capacités cérébrales mais grille l'esprit après 24h d'usage continu." },
    { name: "Manteau Caméléon", description: "Tissu intelligent qui s'adapte à l'environnement pour un camouflage parfait." },
    { name: "Data-Katana", description: "Lame tranchante comme un scalpel. Elle peut aussi trancher des données dans le réseau." },
    { name: "Œil de Faucon", description: "Implant oculaire avec zoom x100, vision nocturne et thermique." },
    { name: "Cœur Synthétique", description: "Remplace le cœur biologique. Il ne se fatigue jamais et pompe du sang enrichi en nanites." },
    { name: "Module d'Effacement", description: "Puce qui efface votre existence des bases de données. Vous devenez un fantôme numérique." },
    { name: "Gantelet Électrique", description: "Gant qui génère des décharges électriques suffisantes pour désactiver n'importe quel système." },
    { name: "Implants Mnésiques", description: "Puce mémoire qui peut stocker des souvenirs entiers. Lecture et écriture possibles." },
  ],
  monsters: [
    "un Cyberpsychoté en pleine crise",
    "un Drone de combat Arasaka",
    "un Super-soldat augmenté",
    "un Chien robotisé aux mâchoires d'acier",
    "une IA de sécurité devenue folle",
    "un Humain transformé en arme biologique",
    "un Essaim de nanobots dévoreurs",
    "une Araignée cybernétique géante",
    "un Clone échappé du laboratoire",
    "un Mercenaire lourdement augmenté",
  ],
};
