import type { GenreContent } from "./types";

export const FANTASY_CONTENT: GenreContent = {
  plotHooks: [
    "Une ancienne prophétie annonce le retour d'un fléau millénaire, et vous en êtes le dernier rempart.",
    "Le roi a été assassiné. Un imposteur siège sur le trône, et seul vous connaissez la vérité.",
    "Un artefact magique a été dérobé du temple sacré. Sans lui, le royaume est condamné.",
    "Les dragons, disparus depuis des siècles, sont soudainement réapparus dans les montagnes.",
    "Une malédiction transforme les habitants en pierre. La source semble venir de la forêt Noire.",
    "Des runes anciennes se sont allumées dans le ciel, annonçant le début du Ragnarök.",
    "Un village entier a disparu du jour au lendemain. Les seules traces mènent à un temple souterrain.",
    "Les récoltes pourrissent et les eaux deviennent noires. Un druide corrompu en est la cause.",
  ],
  locations: [
    { name: "Forêt des Murmures", description: "Sous la canopée, des voix anciennes chuchotent des secrets oubliés. Les arbres centenaires cachent bien des mystères." },
    { name: "Château d'Argent", description: "Forteresse imprenable aux tours scintillantes, gardée par des chevaliers en armure lustrée. Ses couloirs résonnent des pas des héros passés." },
    { name: "Caverne du Dragon", description: "Grotte immense au sommet de la Montagne du Crâne. Des ossements et des trésors s'entassent à l'entrée." },
    { name: "Village d'Emeraude", description: "Havre de paix entouré de champs fertiles. Ses habitants sont accueillants mais quelque chose les inquiète." },
    { name: "Temple des Étoiles", description: "Ruines antiques construites en harmonie avec les astres. Des symboles célestes ornent chaque mur." },
    { name: "Marécages de la Désolation", description: "Terres empoisonnées où brumes toxiques et créatures cauchemardesques rodent sans fin." },
    { name: "Citadelle des Ombres", description: "Forteresse du mal, entourée d'un fossé de lave. Des cris s'échappent de ses donjons." },
    { name: "Porte d'ivoire", description: "Portail dimensionnel gardé par des sphinx. Il mènerait à d'autres mondes." },
    { name: "Bibliothèque Interdite", description: "Sous la montagne, des milliers de grimoires anciens sont conservés. Certains contiennent des savoirs dangereux." },
    { name: "Pics du Crépuscule", description: "Montagnes acérées où seuls les plus courageux s'aventurent. Des aigles géants y nichent." },
    { name: "Vallée des Rois", description: "Nécropole immense où reposent les souverains défunts. Des pièges protègent leurs trésors." },
    { name: "Havre du Phénix", description: "Port rebelle caché dans une crique volcanique. Marchands, pirates et aventuriers s'y côtoient." },
  ],
  npcs: [
    { name: "Eldrin le Sage", role: "conseiller royal", description: "Un vieil homme à la longue barbe blanche, ses yeux bleus pétillent d'une sagesse ancienne." },
    { name: "Lyra l'Éclaireuse", role: "ranger d'élite", description: "Une elfe agile vêtue de vert, son arc en bois de lune ne rate jamais sa cible." },
    { name: "Borin Martel-de-Fer", role: "forgeron nain", description: "Trapu et robuste, ses mains calleuses maîtrisent le feu et le métal comme personne." },
    { name: "Sylfée la Mystique", role: "sorcière des bois", description: "Enveloppée d'une cape de plumes, elle parle aux animaux et lit dans les runes." },
    { name: "Gorim le Colosse", role: "gardien mercenaire", description: "Un demi-géant au cœur tendre malgré son apparence terrifiante. Il vous doit une vie." },
    { name: "Mirabelle la Troubadour", role: "espionne à son compte", description: "Charmeuse et dangereuse, sa lyre cache une dague et ses chansons des secrets." },
    { name: "Frère Theron", role: "paladin errant", description: "Chevalier sacré à l'armure ternie, il cherche la rédemption pour un péché oublié." },
    { name: "Raxis l'Insaisissable", role: "voleur des ombres", description: "On dit qu'il peut traverser n'importe quelle porte sans laisser de trace." },
    { name: "Séléna la Dryade", role: "gardienne de la forêt", description: "Créature végétale aux yeux de miel, elle peut contrôler les plantes et les arbres." },
    { name: "Maître Feng", role: "moine élémentaire", description: "Maître des quatre éléments, son poing frappe aussi fort que le tonnerre." },
    { name: "Reine Aeliana", role: "souveraine des elfes", description: "Noble et fière, son regard perce les mensonges. Elle porte la couronne des étoiles." },
    { name: "Korak le Chasseur", role: "traqueur de monstres", description: "Silhouette massive couverte de cicatrices, il traque les créatures pour la gloire et l'or." },
  ],
  earlyEvents: [
    { text: "Alors que vous avancez sur le chemin, un chariot renversé bloque le passage. Un marchand blessé demande votre aide.", consequence: "Le marchand vous offre une potion de soin en remerciement." },
    { text: "Des bruits de combat retentissent derrière les arbres. Des bandits attaquent une caravane sans défense.", consequence: "Si vous intervenez, les rescapés vous fourniront des informations précieuses." },
    { text: "Un vieux pont de pierre enjambe un ravin dangereux. Il semble instable mais c'est le seul passage.", consequence: "Un passage risqué mais nécessaire pour continuer." },
    { text: "Une clairière abrite un cercle de pierres anciennes. L'énergie magique y est palpable.", consequence: "Vous ressentez une connexion mystique qui renforce votre détermination." },
    { text: "Un ruisseau aux eaux cristallines traverse votre chemin. Une créature aquatique en émerge.", consequence: "La créature, pacifique, vous offre un objet ancien trouvé dans l'eau." },
    { text: "Un garde forestier vous interpelle : des loups géants rodent dans le secteur.", consequence: "Il vous propose de vous guider en échange de compagnie." },
    { text: "Vous trouvez une épée plantée dans un rocher, entourée de lierre. Des runes brillent faiblement.", consequence: "L'épée semble vous choisir — elle vibre lorsque vous l'approchez." },
    { text: "Un vieil ermite vous offre l'hospitalité dans sa cabane. Il connaît l'histoire de la région.", consequence: "Ses récits contiennent des indices sur la quête à venir." },
    { text: "Un autel abandonné émet une lueur douce. Offrir un objet déclenche une vision prophétique.", consequence: "La vision révèle un danger imminent que vous pouvez désormais éviter." },
    { text: "Des traces de pas fraîches mènent à une grotte dissimulée par une cascade.", consequence: "L'exploration de la grotte révèle un passage secret." },
    { text: "Un enfant paniqué court vers vous : sa mère a été enlevée par des créatures de l'ombre.", consequence: "Suivre l'enfant vous mène à un repaire souterrain." },
    { text: "Une tempête magique éclate soudainement, teignant le ciel de couleurs violettes.", consequence: "Vous trouvez refuge dans une tour abandonnée, pleine d'objets magiques." },
  ],
  midEvents: [
    { text: "Le véritable maître des lieux se révèle : un démon antique lié à votre passé. Le sol tremble sous sa puissance.", consequence: "Affronter le démon ou négocier changera le cours de votre quête." },
    { text: "Vous découvrez que votre allié le plus proche vous a trahi pour un pouvoir ancien. Les masques tombent.", consequence: "La trahison vous blesse mais vous apprend une vérité cruciale." },
    { text: "Un artefact maudit corrompt tout sur son passage. Pour le détruire, un sacrifice est nécessaire.", consequence: "La destruction de l'artefact libère une force qui vous marque à jamais." },
    { text: "Les morts se lèvent des tombes. Un nécromancien manipule les âmes des défunts.", consequence: "Chaque ennemi vaincu renforce le pouvoir du nécromancien." },
    { text: "Un portail vers un autre plan dimensionnel s'ouvre devant vous. Des créatures indicibles tentent d'en sortir.", consequence: "Refermer le portail nécessite un rituel dangereux." },
    { text: "Votre quête croise celle d'un autre héros aux objectifs opposés. Le conflit est inévitable.", consequence: "Un duel moral décidera qui poursuit sa route." },
    { text:     "Une prophétie cachée révèle que vous êtes lié au destin du royaume bien plus que vous ne le pensiez.",
    consequence: "Le poids de la prophétie modifie votre perception du monde." },
    { text: "Vous pénétrez dans une cité souterraine où les cristaux lumineux sont la seule source de vie. Des elfes noirs vous observent depuis les ombres.", consequence: "Les elfes noirs vous considèrent comme un intrus. Gagner leur confiance sera un défi." },
    { text: "Un pont magique apparaît sous un arc-en-ciel, menant à un palais flottant dans les nuages.", consequence: "Le palais flottant abrite un oracle qui connaît votre destin." },
    { text: "Un marché gobelin se tient dans une clairière. Marchandises étranges et créatures louches s'y côtoient.", consequence: "Au marché gobelin, informations et artefacts se négocient à prix d'or." },
    { text: "Une source magique aux eaux scintillantes pourrait guérir n'importe quelle blessure — mais un gardien en interdit l'accès.", consequence: "Le gardien de la source vous soumet à une épreuve de pureté d'âme." },
    { text: "Un dragon ancestral émerge de son sommeil millénaire. Son regard vous traverse.", consequence: "Le dragon vous offre un choix : sa puissance ou sa sagesse." },
    { text: "La frontière entre le monde réel et le monde des rêves s'estompe. Les cauchemars prennent vie.", consequence: "Naviguer entre les deux mondes est la seule façon de survivre." },
    { text: "Vous découvrez un laboratoire alchimique secret. Des expériences interdites y ont été menées.", consequence: "Les découvertes du laboratoire pourraient vous donner un avantage décisif." },
    { text: "Un sanctuaire ancien vous soumet à une épreuve de valeur. Les murs se referment.", consequence: "Réussir l'épreuve vous accorde la bénédiction des anciens." },
    { text: "L'armée ennemie marche sur le royaume. Vous devez choisir : défendre la cité ou poursuivre votre mission.", consequence: "Ce choix déterminera votre réputation pour le reste de l'aventure." },
  ],
  climaxEvents: [
    { text: "Le seigneur démon vous attend dans sa salle du trône, entouré de ses lieutenants. L'air brûle autour de lui.", consequence: "Le combat final décidera du sort du royaume." },
    { text: "L'artefact que vous cherchez est à portée de main, mais activer le nécessite un sacrifice ultime.", consequence: "Le pouvoir a un prix, et il est plus élevé que vous ne l'imaginiez." },
    { text: "Le sort du monde repose sur une seule décision : libérer le pouvoir ancien ou le sceller à jamais.", consequence: "Cette décision résonnera pendant des millénaires." },
    { text: "Le ciel s'assombrit tandis que la lune se teinte de rouge. Le portail final s'ouvre dans les cieux.", consequence: "L'affrontement final dépasse tout ce que vous avez connu." },
    { text: "Votre ennemi vous révèle la vérité : vous combattez le mauvais camp depuis le début. Tout est remis en question.", consequence: "La vérité change tout, mais est-il trop tard ?" },
    { text: "Les dieux eux-mêmes observent votre combat. Votre victoire ou défaite aura des conséquences divines.", consequence: "Les dieux jugent vos actions. Votre héritage est en jeu." },
    { text: "Une vague d'énergie pure déferle sur le champ de bataille. Le temps semble suspendu.", consequence: "Dans ce moment hors du temps, vous devez faire votre choix final." },
    { text: "Le mal ancestral se manifeste sous sa forme véritable, une créature d'une puissance incommensurable.", consequence: "Toutes vos compétences sont mises à l'épreuve dans ce combat surhumain." },
  ],
  twists: [
    "Le mentor qui vous a guidé jusqu'ici recherche en réalité le même artefact pour ses propres desseins.",
    "La malédiction qui frappe le royaume n'est pas une punition divine mais une expérience alchimique ayant mal tourné.",
    "Le véritable méchant est votre reflet miroir venu d'une dimension parallèle.",
    "L'élu de la prophétie n'est pas vous — vous êtes le protecteur de l'élu, et il est en danger.",
    "Les monstres que vous combattez sont en fait d'anciens héros transformés par une malédiction.",
    "Le royaume que vous cherchez à sauver est déjà corrompu de l'intérieur par un culte secret.",
    "L'artefact que vous devez détruire est en réalité le seul objet capable de maintenir l'équilibre du monde.",
    "Le sage qui vous conseille est en réalité un dragon millénaire qui teste votre valeur.",
    "La princesse que vous devez sauver est en réalité la maîtresse du démon que vous combattez.",
  ],
  endings: [
    { text: "Le royaume est sauvé, mais vous avez perdu une partie de vous-même dans la bataille.", condition: "Votre nom est gravé dans la légende, mais le prix à payer était lourd. Les cicatrices, visibles et invisibles, vous rappelleront chaque jour votre sacrifice." },
    { text: "Vous avez triomphé et rapporté la paix dans le royaume.", condition: "Les cloches sonnent dans tout le pays. Vous êtes acclamé comme un héros. Une nouvelle ère de prospérité commence, et vous en êtes l'artisan." },
    { text: "Vous choisissez de vous exiler, emportant avec vous le secret du mal pour qu'il ne nuise plus jamais.", condition: "Personne ne saura jamais ce que vous avez fait. Votre sacrifice silencieux protège le royaume depuis l'ombre, à jamais." },
    { text: "Le pouvoir était trop grand pour y résister. Vous prenez la place du démon, devenant le nouveau maître des ténèbres.", condition: "Le bien et le mal se confondent. Vous régnez désormais sur ce que vous juriez de détruire." },
    { text: "Vous réunissez les peuples du royaume sous une même bannière, mettant fin à des siècles de guerre.", condition: "L'alliance que vous avez forgée résiste à l'épreuve du temps. Vous devenez le symbole de l'unité." },
    { text: "La quête n'était qu'un rêve, ou peut-être pas. Vous vous réveillez sans savoir ce qui est réel.", condition: "Était-ce réel ou imaginaire ? Les souvenirs de votre aventure s'estompent, mais la sagesse acquise demeure." },
    { text: "Vous sacrifiez votre magie pour sceller le mal à jamais, devenant un simple mortel.", condition: "La paix a un prix : votre essence magique. Vous vivez le reste de vos jours comme un humain ordinaire, mais libre." },
  ],
  choiceSets: [
    ["Avancer prudemment", "Charger sans réfléchir", "Chercher une autre voie"],
    ["Parler pacifiquement", "Montrer votre puissance", "Rester en embuscade"],
    ["Utiliser un sort", "Dégainer votre arme", "Tendre un piège"],
    ["Suivre la piste", "Interroger les locaux", "Étudier la carte"],
    ["Prendre par la montagne", "Passer par la forêt", "Suivre la rivière"],
    ["Faire confiance à votre instinct", "Écouter les conseils", "Suivre la logique"],
    ["Négocier une trêve", "Attaquer de nuit", "Chercher des renforts"],
    ["Inspecter les ruines", "Fouiller les environs", "Interroger les témoins"],
    ["Utiliser la ruse", "Compter sur votre force", "Faire appel à la magie"],
    ["Protéger les innocents", "Poursuivre l'ennemi", "Sécuriser la zone"],
  ],
  artifacts: [
    { name: "Épée du Crépuscule", description: "Forgée dans un météore, elle brille d'une lueur bleutée la nuit." },
    { name: "Bouclier d'Écailles", description: "Fabriqué à partir d'écailles de dragon, il résiste à tout feu." },
    { name: "Amulette du Temps", description: "Permet de ralentir le temps quelques instants une fois par jour." },
    { name: "Grimoire des Ombres", description: "Contient des sorts interdits qui puisent dans l'énergie vitale." },
    { name: "Anneau de l'Aube", description: "Restaure l'énergie et purifie les poisons au lever du soleil." },
    { name: "Corne de Ralliement", description: "Son appel traverse les montagnes pour rassembler des alliés." },
    { name: "Larmes de la Lune", description: "Gouttes d'argent gelées qui guérissent les blessures les plus graves." },
    { name: "Masque du Métamorphe", description: "Permet de prendre l'apparence de n'importe qui vu une fois." },
  ],
  monsters: [
    "un Troll des cavernes",
    "une Meute de Loups-Garous",
    "un Golem de pierre",
    "une Harpie furieuse",
    "un Basilic aux yeux pétrifiants",
    "un Chimère crachant du feu",
    "un Spectre des tombeaux",
    "une Araignée géante des bois",
    "un Minotaure enragé",
    "une Gorgone au regard mortel",
  ],
};
