import type { GenreContent } from "./types";

export const HORROR_CONTENT: GenreContent = {
  plotHooks: [
    "Un manoir abandonné réapparaît chaque nuit au même endroit. Ses fenêtres illuminées appellent les curieux.",
    "Les habitants disparaissent un par un. On retrouve leurs vêtements pliés, rien d'autre.",
    "Une vidéo trouvée dans le grenier montre votre propre enterrement il y a dix ans.",
    "L'hôpital psychiatrique désaffecté émet des signaux radio. Une voix supplie qu'on la libère.",
    "Un livre ancien trouvé dans une brocante parle de vous, en détail, avant même votre naissance.",
    "Dans ce village, les enfants naissent avec les yeux noirs. Personne n'ose en parler.",
    "Un tunnel de métro oublié mène à une version parallèle de la ville, déserte et silencieuse.",
    "Chaque nuit à 3h03, le téléphone sonne. C'est toujours vous, de demain, qui suppliez de ne pas répondre.",
  ],
  locations: [
    { name: "Manoir Blackwell", description: "Bâtisse victorienne aux fenêtres brisées. Des cris étouffés s'échappent des caves." },
    { name: "Hôpital psychiatrique de Ravenbrook", description: "Couloirs sans fin, salles d'opération abandonnées. L'écho de traitements oubliés." },
    { name: "Forêt du Crépuscule", description: "Les arbres y ont des visages. La nuit, ils bougent quand on ne les regarde pas." },
    { name: "Église Saint-Null", description: "Édifice gothique aux vitraux brisés. L'autel dégage une présence malveillante." },
    { name: "Cimetière des Âmes Perdues", description: "Tombes anciennes aux épitaphes effacées par le temps. Certaines sont ouvertes." },
    { name: "Station de métro abandonnée", description: "Quai désert, affiches jaunies. Un train fantôme y circore encore." },
    { name: "Laboratoire souterrain", description: "Installation secrète aux murs tachés de sang. Des expériences innommables y ont eu lieu." },
    { name: "Orphelinat des Oubliés", description: "Balancelles qui grincent toutes seules. Des rires d'enfants dans les pièces vides." },
    { name: "La ville fantôme de Pripiat", description: "Cité abandonnée où le temps s'est arrêté. Quelque chose rôde dans le silence." },
    { name: "Les égouts de la vieille ville", description: "Labyrinthes obscurs où résonnent des chuchotements. Les ombres y sont plus épaisses." },
  ],
  npcs: [
    { name: "Le Conservateur", role: "gardien du manoir", description: "Un homme voûté à la peau cireuse. Il sait tout sur les lieux mais ne dit rien." },
    { name: "Mme Rosewood", role: "médium locale", description: "Une vieille femme aux yeux laiteux. Elle parle aux morts, et parfois ils répondent." },
    { name: "L'inspecteur Valcourt", role: "enquêteur sceptique", description: "Dévoué mais marqué par les horreurs qu'il a vues. Il cache ses blessures." },
    { name: "Sœur Agathe", role: "religieuse exorciste", description: "Son chapelet est en os de saints. Elle a vu le mal de près." },
    { name: "Docteur Morgenstern", role: "ancien psychiatre", description: "Il travaillait à Ravenbrook. Ses méthodes étaient... controversées." },
    { name: "Le Marchand d'ombres", role: "collectionneur d'artefacts maudits", description: "On ne voit jamais son visage sous son chapeau. Sa boutique n'existe que la nuit." },
    { name: "Elara la Voyante", role: "aveugle qui voit l'invisible", description: "Ses yeux sont voilés de blanc. Elle lit l'avenir dans les cendres." },
    { name: "Le Bibliothécaire", role: "gardien des savoirs interdits", description: "Il n'a pas cligné des yeux depuis qu'il a ouvert le livre maudit." },
    { name: "L'Enfant Fantôme", role: "esprit du lieu", description: "Petite fille en robe blanche, elle fredonne une comptine oubliée." },
    { name: "Le Fossoyeur", role: "gardien du cimetière", description: "Homme silencieux à la pelle toujours prête. Il creuse des tombes depuis si longtemps qu'il ne se souvient plus d'avoir été vivant." },
    { name: "Mme Delacroix", role: "voyante aveugle", description: "Ses yeux vides voient ce que les vivants ne peuvent pas voir. Elle lit l'avenir dans les cendres." },
    { name: "Le Shérif Hawkins", role: "homme de loi local", description: "Il refuse de croire au surnaturel, mais il a vu des choses dont il ne parle jamais." },
  ],
  earlyEvents: [
    { text: "Une porte grince derrière vous. Vous vous retournez : le couloir est vide, mais une empreinte de main apparaît sur le mur.", consequence: "L'empreinte est fraîche. Quelque chose vous suit." },
    { text: "Un téléphone sonne dans une cabine poussiéreuse. Personne dans la rue. Vous décrochez.", consequence: "Une voix chuchote votre nom et vous met en garde contre ce qui vient." },
    { text: "En ouvrant un tiroir, vous trouvez un journal intime. La dernière entrée date d'il y a un siècle.", consequence: "Le journal décrit des événements qui se reproduisent en ce moment même." },
    { text: "Une photo de groupe dans un cadre argenté. Tous les visages sont grattés sauf un — le vôtre.", consequence: "La photo a été prise avant votre naissance. Vous fixez votre propre visage." },
    { text: "Les lumières vacillent. Dans le noir complet, une voix d'enfant dit : 'Tu n'aurais pas dû venir.'", consequence: "Quand la lumière revient, une petite empreinte de main est sur votre épaule." },
    { text: "Un miroir ancien reflète une pièce différente de celle où vous êtes.", consequence: "En touchant le miroir, la pièce reflétée vous est étrangement familière." },
    { text: "Vous trouvez une clé rouillée avec un numéro gravé : 1313. Elle semble ancienne.", consequence: "La clé correspond à une porte que personne n'a ouverte depuis des décennies." },
    { text: "Un pendule se balance tout seul dans une pièce fermée à clé. Il s'arrête brusquement quand vous entrez.", consequence: "Le pendule indique une direction précise. Comme s'il vous guidait." },
    { text: "Le sol craque sous vos pas. En regardant sous les lattes, vous trouvez une mèche de cheveux blonds attachée par un ruban rouge.", consequence: "Les cheveux portent encore une brosse. Ils sont vivants." },
    { text: "Un corbeau frappe à la fenêtre, encore et encore. Il tient dans son bec un morceau de tissu ensanglanté.", consequence: "Le tissu porte un nom brodé — le vôtre." },
  ],
  midEvents: [
    { text: "Vous rêvez de votre propre mort chaque nuit, avec des détails de plus en plus précis. Ce matin, vous avez retrouvé la blessure sur votre corps.", consequence: "Le rêve et la réalité fusionnent. Vous ne savez plus où vous êtes en sécurité." },
    { text: "Un tableau représentant une scène de chasse change lentement. Les personnages se rapprochent du premier plan.", consequence: "Ils vous regardent maintenant. Leurs yeux suivent vos mouvements." },
    { text: "Votre reflet dans le miroir ne suit plus vos mouvements. Il sourit. Vous ne souriez pas.", consequence: "Votre reflet vous montre des choses que vous avez oubliées. Ou que vous n'avez jamais vues." },
    { text: "Les murs de la pièce se rapprochent imperceptiblement. La porte a disparu.", consequence: "Vous êtes piégé dans un espace qui rétrécit. Chaque minute compte." },
    { text: "Un rituel décrit dans le journal nécessite un sacrifice. Le vôtre. Les symboles au sol s'illuminent.", consequence: "Le rituel a commencé sans vous. Vous n'êtes qu'un invité." },
    { text: "Vous trouvez une cassette vidéo. En la regardant, vous vous voyez dans la même pièce, il y a une heure.", consequence: "Dans la vidéo, quelque chose est derrière vous, que vous n'aviez pas vu." },
    { text: "Le temps s'inverse par moments. Vous revivez les dernières minutes sans pouvoir changer quoi que ce soit.", consequence: "Chaque boucle vous affaiblit un peu plus. Le temps est une prison." },
    { text:     "Un rituel de protection que vous avez effectué plus tôt était en réalité une invocation. Vous avez fait entrer l'entité.",
    consequence: "Les symboles que vous avez tracés étaient inversés. L'entité est maintenant libre." },
    { text: "Une chambre d'enfant cachée derrière un mur. Les jouets sont encore chauds. Une balançoire grince toute seule.", consequence: "La présence d'un enfant mort hante cette pièce. Il veut jouer." },
    { text: "Vous trouvez une cassette audio. En l'écoutant, vous entendez votre propre voix enregistrer un message que vous n'avez jamais fait.", consequence: "La cassette contient des instructions pour survivre à ce qui va arriver. Mais qui les a enregistrées ?" },
    { text: "Les escaliers de l'immeuble se répètent en boucle. Vous passez devant la même porte pour la dixième fois.", consequence: "L'espace est piégé dans une boucle. Chaque tentative vous fatigue un peu plus." },
    { text: "Un téléphone mural sonne dans un couloir vide. La voix au bout du fil connaît votre nom et votre peur la plus profonde.", consequence: "La voix au téléphone vous donne des informations que vous seul pourriez connaître." },
    { text: "Vous découvrez que vous n'êtes pas seul dans votre corps. Une autre conscience émerge.", consequence: "Parfois c'est vous qui contrôlez vos actions. Parfois non." },
    { text: "Les morts que vous avez croisés ne sont pas morts. Ils font partie d'un cycle dont vous êtes le prochain maillon.", consequence: "Chaque victime que vous découvrez était à votre place avant vous." },
  ],
  climaxEvents: [
    { text: "L'entité se révèle enfin. Elle a votre visage. Elle était vous depuis le début.", consequence: "L'horreur suprême : vous êtes votre propre ennemi. L'affrontement est intérieur." },
    { text: "Le rituel final approche. Cinq victimes, cinq bougies. La sixième est pour vous.", consequence: "Le cercle se ferme. Vous êtes à la fois le sacrifice et le sacrificateur." },
    { text: "La vérité éclate : cet endroit est une boucle temporelle. Vous avez déjà vécu cette fin des centaines de fois.", consequence: "La seule façon d'en sortir est de faire un choix que vous n'avez jamais fait." },
    { text: "L'horreur n'était pas surnaturelle mais humaine. Un expérimentateur fou a orchestré chaque peur.", consequence: "Affronter l'homme derrière le rideau est plus terrifiant que n'importe quel monstre." },
    { text: "Le monde réel se fissure. Les murs saignent. La réalité elle-même se désagrège autour de vous.", consequence: "Vous devez trouver l'ancre qui maintient votre existence avant qu'il ne soit trop tard." },
    { text: "Vous atteignez le cœur des ténèbres. L'entité primordiale vous attend, indifférente et immense.", consequence: "Face à l'incommensurable, votre courage est votre seule arme." },
    { text: "Chaque personne que vous avez rencontrée était une manifestation de l'entité. Il n'y a jamais eu personne d'autre.", consequence: "La solitude absolue est la véritable horreur. Vous êtes seul dans ce cauchemar." },
  ],
  twists: [
    "Le manoir n'est pas hanté — il est vivant. Il absorbe les souvenirs de ses visiteurs.",
    "Vous n'êtes pas en train d'enquêter sur des disparitions. Vous êtes les disparitions. Vous êtes mort depuis le début.",
    "La créature que vous fuyez est en fait votre propre conscience, matérialisée par votre peur.",
    "Les victimes ne sont pas mortes. Elles ont été absorbées par la maison et vivent dans les murs.",
    "L'entité maléfique n'existe pas. C'est une hallucination collective causée par un gaz toxique dans les fondations.",
    "Vous n'avez jamais quitté votre lit d'hôpital. Tout est le fruit de votre esprit en coma.",
    "Le véritable monstre est celui qui vous a envoyé ici — il savait depuis le début et voulait se débarrasser de vous.",
  ],
  endings: [
    { text: "Vous vous échappez, mais quelque chose est revenu avec vous.", condition: "De retour dans le monde réel, vous n'êtes plus seul. Une ombre vous suit partout. Vous apprenez à vivre avec." },
    { text: "Vous devenez le nouveau gardien des lieux, protégeant les prochains visiteurs de la vérité.", condition: "Le cycle continue. Vous prenez la place du précédent gardien. Peut-être qu'un jour, quelqu'un vous libérera." },
    { text: "La réalité se reconstruit autour de vous. Vous avez survécu, mais les cauchemars persistent.", condition: "Chaque nuit, vous y retournez en rêve. Chaque matin, une nouvelle marque sur votre corps." },
    { text: "Vous détruisez le mal à la source, disparaissant avec lui dans le néant.", condition: "Votre sacrifice referme la porte sur l'horreur pour toujours. Personne ne saura jamais ce que vous avez fait." },
    { text: "Le cauchemar continue. Vous êtes piégé dans une boucle éternelle, conscient de chaque répétition.", condition: "Vous avez tout vécu des centaines de fois. Chaque fois, vous espérez que ce sera la dernière." },
    { text: "L'entité vous propose un marché : votre liberté contre celle d'un autre. Vous acceptez.", condition: "Vous êtes libre, mais quelqu'un d'autre est à votre place. Vous ne saurez jamais qui." },
  ],
  choiceSets: [
    ["Allumer une lampe torche", "Avancer dans le noir", "Faire demi-tour"],
    ["Ouvrir la porte", "Écouter derrière la porte", "Chercher une autre issue"],
    ["Crier pour signaler votre présence", "Rester silencieux", "Vous cacher"],
    ["Examiner l'objet", "Le laisser tranquille", "Le prendre avec vous"],
    ["Suivre le bruit", "Fuir dans la direction opposée", "Vous figer sur place"],
    ["Allumer une bougie", "Utiliser votre téléphone", "Rester dans l'obscurité"],
    ["Lire le document", "Brûler le document", "Le cacher"],
    ["Vous cacher et observer", "Affronter ce qui arrive", "Tenter de vous enfuir"],
    ["Faire confiance à l'inconnu", "Vous méfier et garder vos distances", "L'attaquer avant qu'il n'attaque"],
    ["Inspecter le cadavre", "Appeler les secours", "Quitter les lieux immédiatement"],
  ],
  artifacts: [
    { name: "Le Journal des Ombres", description: "Ses pages changent de contenu chaque nuit." },
    { name: "La Bougie d'Âme", description: "Sa flamme vacille quand un esprit est proche." },
    { name: "Le Miroir de Vérité", description: "Reflète ce qui est caché, pas ce qui est devant." },
    { name: "La Clé Squelette", description: "Ouvre n'importe quelle porte, mais à quel prix ?" },
    { name: "L'Encens de Protection", description: "Sa fumée repousse les entités pendant quelques minutes." },
    { name: "Le Pendule de Localisation", description: "Pointe toujours vers la source du mal." },
  ],
  monsters: [
    "une Créature sans visage",
    "un Chien noir aux yeux rouges",
    "une Femme en blanc glissant sur le sol",
    "un Enfant à la voix d'adulte",
    "une Ombre qui rampe sur les murs",
    "un Homme au chapeau melon",
    "une Marionnette désarticulée",
    "un Masque souriant vide",
    "une Silhouette trop grande",
    "un Ami qui n'existe pas",
  ],
};
