import type { GenreContent } from "./types";

export const MYTHOLOGIQUE_CONTENT: GenreContent = {
  plotHooks: [
    "Zeus lui-même vous apparaît en songe. Les dieux de l'Olympe sont en guerre, et vous devez choisir votre camp.",
    "Un oracle annonce qu'un mortel renversera les Titans. Les monstres antiques se réveillent pour vous éliminer.",
    "Le casque d'Hadès a été volé. Sans lui, l'équilibre entre la vie et la mort est brisé.",
    "Les neuf muses ont perdu la voix. Sans elles, l'inspiration disparaît du monde.",
    "Une malédiction d'Anubis frappe la vallée du Nil. Les morts refusent de quitter le monde des vivants.",
    "Le marteau de Thor a disparu. Sans lui, les géants de glace envahiront Midgard.",
    "Le serpent Jörmungandr se réveille au fond des océans. Le Ragnarök est-il proche ?",
    "Un héros légendaire est mort. Les dieux vous choisissent comme son successeur. Saurez-vous être à la hauteur ?",
  ],
  locations: [
    { name: "Mont Olympe", description: "Royaume céleste des dieux grecs. Palais de marbre blanc sous un ciel éternellement bleu." },
    { name: "Labyrinthe du Minotaure", description: "Dédale sans fin sous Cnossos. Les murs suintent et des os blanchis tapissent le sol." },
    { name: "Forêt d'Yggdrasil", description: "Arbre-monde nordique dont les branches relient les neuf royaumes." },
    { name: "Vallée des Rois", description: "Nécropole égyptienne aux tombeaux regorgeant de pièges et de trésors." },
    { name: "Temple de Delphes", description: "Sanctuaire de l'oracle où les fumées révèlent l'avenir à ceux qui savent écouter." },
    { name: "Royaume d'Hadès", description: "Monde souterrain où les âmes des morts errent éternellement. Le Styx en est la frontière." },
    { name: "Asgard", description: "Cité dorée des dieux nordiques, reliée à Midgard par le pont arc-en-ciel Bifröst." },
    { name: "Île de Crète", description: "Terre natale des héros, où les dieux marchent encore parmi les humains." },
    { name: "Le Nil éternel", description: "Fleuve sacré d'Égypte, ses eaux portent les secrets des pharaons et des dieux anciens." },
    { name: "Jotunheim", description: "Royaume des géants de glace, étendue gelée où seuls les plus forts survivent." },
    { name: "Atlantide", description: "Cité engloutie aux dômes de cristal. Les Atlantes possèdent un savoir interdit." },
    { name: "Le Jardin des Hespérides", description: "Verger divin où poussent les pommes d'or de l'immortalité, gardé par un dragon." },
  ],
  npcs: [
    { name: "Chiron le Centaure", role: "sage précepteur", description: "Mi-homme mi-cheval, il a formé les plus grands héros grecs. Sa sagesse est infinie." },
    { name: "Sibylle de Delphes", role: "oracle", description: "Prêtresse aux yeux voilés, elle parle la langue des dieux en transe." },
    { name: "Valkyrie Brynhilde", role: "guerrière céleste", description: "Vierge guerrière au casque ailé, elle choisit les héros dignes du Valhalla." },
    { name: "Anubis", role: "dieu des morts", description: "Divinité à tête de chacal, gardien des âmes et de l'équilibre entre les mondes." },
    { name: "Hercule", role: "demi-dieu", description: "Fils de Zeus à la force prodigieuse. Il cherche à expier ses péchés par des exploits." },
    { name: "Méduse", role: "gardienne maudite", description: "Gorgone aux serpents dans les cheveux. Son regard pétrifie quiconque croise ses yeux." },
    { name: "Odin le Vagabond", role: "père des dieux", description: "Dieu borgne voyageant déguisé en vieillard. Il cherche la sagesse plus que le pouvoir." },
    { name: "Nérée", role: "vieillard de la mer", description: "Divinité marine capable de prédire l'avenir. Il change de forme pour échapper aux questions." },
    { name: "Isis", role: "déesse de la magie", description: "Maîtresse des sorts et des enchantements, elle protège les héros courageux." },
    { name: "Loki", role: "dieu farceur", description: "Tricheur divin à la langue acérée. Ses plans compliqués servent souvent ses propres intérêts." },
  ],
  earlyEvents: [
    { text: "Un aigle géant vous survole et lâche un rameau d'olivier. Un message divin ?", consequence: "Le rameau est un signe d'Athéna. Elle vous invite à la suivre." },
    { text: "Vous croisez un vieillard boiteux qui vous pose trois énigmes. Ses yeux luisent d'une lueur dorée.", consequence: "Le vieillard est un dieu déguisé. Résoudre ses énigmes vous apporte sa bénédiction." },
    { text: "Une nymphe émerge d'une rivière. Elle vous offre une épée ancienne enchâssée de saphirs.", consequence: "L'épée est forgée par Héphaïstos. Elle ne peut être brisée." },
    { text: "Les statues d'un temple prennent vie. Elles vous parlent avec la voix des dieux.", consequence: "Les dieux vous mettent en garde contre un danger que vous seuls pouvez vaincre." },
    { text: "Un oracle propose de lire votre avenir. Les cartes montrent une couronne brisée et un phénix.", consequence: "L'oracle voit une destinée hors du commun. Vous êtes marqué par les dieux." },
    { text: "Une hydre attaque un village côtier. Ses têtes repoussent à mesure qu'on les coupe.", consequence: "Chaque tête coupée en produit deux. Le feu est la seule arme efficace." },
    { text: "Vous trouvez une pomme d'or dans une clairière. La cueillir déclenche un piège divin.", consequence: "La pomme est un test des dieux. La rendre à son propriétaire vous évite leur courroux." },
    { text: "Le sol tremble. Un titan enchaîné sous la montagne tente de se libérer.", consequence: "Les chaînes s'affaiblissent. Quelqu'un nourrit le titan de magie interdite." },
    { text: "Une sirène chante sur les rochers. Son chant promet la gloire éternelle.", consequence: "Le chant de la sirène est irrésistible. Y résister prouve votre force de caractère." },
    { text: "Un cercle de pierres anciennes s'illumine au coucher du soleil. Un portail vers un autre royaume.", consequence: "Le portail mène à Alfheim, le royaume des elfes de lumière." },
    { text: "Un cerf blanc aux bois d'argent traverse votre chemin. Le suivre vous mène à une source sacrée.", consequence: "Boire de la source sacrée guérit toutes les blessures et accorde une vision prophétique." },
    { text: "Un combat de gladiateurs dans un cirque romain cache un complot contre l'empereur.", consequence: "Les gladiateurs sont des esclaves rebelles. Les rejoindre vous met hors-la-loi." },
  ],
  midEvents: [
    { text: "Les dieux vous soumettent à une épreuve : accomplir douze travaux impossibles.", consequence: "Chaque travail achevé vous rapproche de l'immortalité. Chaque échec vous coûte une année de vie." },
    { text: "Le destin du monde est lié à une prophétie. Vous devez empêcher son accomplissement — ou le réaliser.", consequence: "La prophétie parle de vous. Essayer de l'éviter est peut-être ce qui la réalisera." },
    { text: "Un dieu jaloux vous transforme en animal. Vous devez retrouver votre forme humaine.", consequence: "Sous forme animale, vous découvrez des secrets que les humains ne voient pas." },
    { text: "L'armée des morts marche sur le monde des vivants. Hadès a brisé le pacte.", consequence: "Les morts réclament leur place parmi les vivants. La frontière entre les mondes s'estompe." },
    { text: "Un artefact divin est fragmenté en trois parties, cachées aux trois coins du monde connu.", consequence: "Réunir les fragments attire l'attention des dieux... et des monstres." },
    { text: "Votre famille est retenue en otage par un roi impie qui défie les dieux.", consequence: "Le roi impie possède une arme divine volée. Les dieux ne peuvent pas intervenir." },
    { text: "Un fléau divin frappe la terre : sécheresse, peste, inondations. Les dieux sont en colère.", consequence: "Apaiser les dieux nécessite un sacrifice. Mais lequel accepteront-ils ?" },
    { text: "Le Minotaure s'échappe du labyrinthe. Il terrorise la campagne.", consequence: "Traquer le Minotaure est dangereux mais nécessaire. Son retour dans le labyrinthe est la seule solution." },
    { text: "Un serpent géant encerclé le monde. Ses mâchoires se referment sur les océans.", consequence: "Le serpent de Midgard se prépare pour le Ragnarök. Les signes sont là." },
    { text: "La boîte de Pandore est ouverte. Les maux s'abattent sur l'humanité. Seul l'espoir reste.", consequence: "L'espoir est la plus puissante des armes. Mais aussi la plus cruelle des illusions." },
    { text: "Un héros tombé au combat cherche à revenir des Enfers. Vous devez l'aider à traverser le Styx.", consequence: "Le passeur Charon exige un paiement. Une âme contre une autre." },
    { text: "Les Amazones déclarent la guerre aux royaumes voisins. Leur reine possède la ceinture d'Arès.", consequence: "La ceinture d'Arès rend invincible. Voler la ceinture est la clé de la paix." },
  ],
  climaxEvents: [
    { text: "Les Titans s'éveillent. Leur colère menace de détruire l'Olympe et le monde des mortels.", consequence: "Les dieux et les mortels doivent s'unir. La Titanomachie est sur le point de recommencer." },
    { text: "Le Ragnarök commence. Le ciel s'assombrit, les monstres se déchaînent, les héros tombent.", consequence: "La fin du monde est aussi un commencement. Votre place au Valhalla est-elle méritée ?" },
    { text: "Atlas accepte de lâcher le ciel si quelqu'un prend sa place. Un sacrifice éternel.", consequence: "Soutenir le ciel est une torture éternelle. Mais sans Atlas, l'univers s'effondre." },
    { text: "Le verrou des Enfers est brisé. Les âmes damnées s'échappent et possèdent les vivants.", consequence: "Refermer les Enfers nécessite de sceller la brèche avec du sang divin." },
    { text: "Le dieu suprême vous offre l'immortalité. Mais accepter signifie servir les dieux pour toujours.", consequence: "L'immortalité est un cadeau empoisonné. Les héros vivent éternellement, mais regardent leurs proches mourir." },
    { text: "L'équilibre du monde est rompu. Chaos et Ordre s'affrontent dans une guerre cosmique.", consequence: "Vous devez choisir votre camp. Le chaos offre la liberté, l'ordre offre la sécurité." },
    { text: "Le temps s'arrête. Les dieux figent l'humanité pour juger sa valeur.", consequence: "Le jugement des dieux déterminera si l'humanité mérite de survivre." },
  ],
  twists: [
    "Le véritable oracle est un imposteur. Les prophéties sont manipulées par un titan déguisé.",
    "Vous êtes la réincarnation d'un héros légendaire dont les souvenirs refont surface.",
    "Les dieux ne sont pas immortels. Ils peuvent être tués, et quelqu'un les chasse un par un.",
    "Le monstre que vous traquez est en fait un dieu maudit qui cherche à briser sa malédiction.",
    "Votre ennemi juré est votre frère perdu, transformé par la magie noire.",
    "Le monde n'a qu'un seul dieu, et il vous parle depuis le début à travers toutes les religions.",
    "Le Ragnarök n'est pas une fin mais un recommencement. Les mêmes événements se répètent en boucle.",
  ],
  endings: [
    { text: "Vous prenez place parmi les dieux sur l'Olympe, immortel et respecté pour l'éternité.", condition: "Votre nom est chanté par les poètes pour les millénaires à venir. Vous avez gagné l'immortalité." },
    { text: "Vous sacrifiez votre vie pour sauver l'humanité, devenant une légende éternelle.", condition: "Les héros meurent jeunes mais vivent pour toujours dans les cœurs. Votre sacrifice est gravé dans la mémoire du monde." },
    { text: "Vous refusez l'immortalité et vivez le reste de vos jours en simple mortel, mais en paix.", condition: "La sagesse du héros : mourir en paix vaut mieux que vivre éternellement dans le conflit." },
    { text: "Vous unifiez les panthéons, créant une alliance entre les dieux grecs, nordiques et égyptiens.", condition: "Une nouvelle ère de coopération divine commence. Les frontières entre les mythologies s'estompent." },
    { text: "Vous devenez le gardien du savoir interdit, protégeant les secrets des dieux des mortels indignes.", condition: "Les mystères des dieux sont entre vos mains. Vous guidez l'humanité depuis l'ombre." },
    { text: "Vous brisez le cycle du destin, donnant aux mortels le libre arbitre pour la première fois.", condition: "Sans destinée écrite, les humains sont libres de créer leur propre chemin. Vous les avez libérés." },
    { text: "Le Ragnarök s'achève. Un nouveau monde émerge des cendres, et vous en êtes le père fondateur.", condition: "La fin du monde était une renaissance. La nouvelle Terre vous appartient." },
  ],
  choiceSets: [
    ["Prier les dieux", "Compter sur votre force", "Consulter l'oracle"],
    ["Combattre le monstre", "Le contourner", "Négocier avec lui"],
    ["Accepter l'aide divine", "Refuser l'ingérence des dieux", "Faire un sacrifice"],
    ["Entrer dans le labyrinthe", "Le brûler", "Attendre la sortie du monstre"],
    ["Libérer le titan", "Le garder enchaîné", "Le tuer"],
    ["Traverser le Styx", "Suivre le fleuve", "Construire un radeau"],
    ["Voler l'artefact", "Le détruire", "Le cacher"],
    ["Soutenir Athéna", "Soutenir Arès", "Rester neutre"],
  ],
  artifacts: [
    { name: "Épée Excalibur", description: "Lame divine forgée dans le feu des dieux. Elle ne manque jamais sa cible." },
    { name: "Toison d'Or", description: "Peau de bélier magique qui guérit toutes les blessures et apporte la prospérité." },
    { name: "Casque des Ombres", description: "Casque d'Hadès rendant invisible quiconque le porte." },
    { name: "Sandales d'Hermès", description: "Sandales ailées permettant de voler et de se déplacer à la vitesse du vent." },
    { name: "Marteau de Forge", description: "Arme d'Héphaïstos capable de créer n'importe quel objet en un seul coup." },
    { name: "Cor de Heimdall", description: "Cor dont le son traverse les neuf mondes. Son appel rassemble les héros." },
    { name: "Ceinture de Freyja", description: "Ceinture magique qui décuple la beauté et le charisme de son porteur." },
    { name: "Bâton de Thot", description: "Sceptre égyptien contenant toute la connaissance du monde." },
  ],
  monsters: [
    "le Minotaure au corps d'homme et tête de taureau",
    "l'Hydre aux neuf têtes",
    "un Cyclope géant à l'œil unique",
    "le Chien Cerbère à trois têtes",
    "une Harpie aux serres acérées",
    "un Griffon au bec d'aigle",
    "le Serpent Jörmungandr",
    "un Sphinx poseur d'énigmes",
    "une Chimère crachant du feu",
    "un Loup Fenrir à la mâchoire démesurée",
  ],
};
