import type { GenreContent } from "./types";

export const PIRATE_CONTENT: GenreContent = {
  plotHooks: [
    "Une carte au trésor tatouée sur le dos d'un prisonnier. Elle mène à la rançon du roi des pirates.",
    "Le galion fantôme du Capitaine Barbe-Noire est aperçu tous les cent ans. Cette nuit est la bonne.",
    "La flotte royale encerclait votre port. Le seul moyen de survivre : devenir pirate.",
    "Un kraken légendaire protège l'épave d'un navire rempli d'or. Vous avez besoin d'un équipage.",
    "Votre frère a été enlevé par des pirates rivaux. La rançon est la carte d'une île maudite.",
    "Une sirène vous sauve d'une noyade. En échange, elle vous demande de libérer ses sœurs prisonnières.",
    "Le gouverneur corrompu de Port-Royal met à prix la tête de tous les pirates. La chasse à l'homme commence.",
    "Un seigneur anglais propose une amnistie à tout pirate qui rapporte le trésor du légendaire capitaine Flint.",
  ],
  locations: [
    { name: "Port-Royal", description: "Repaire de pirates où l'odeur du rhum et de la poudre à canon flotte dans chaque rue. Les tavernes ne désemplissent jamais." },
    { name: "Île du Crâne", description: "Île volcanique entourée de récifs acérés. On dit que Flint y a caché son plus grand trésor." },
    { name: "La Mer des Larmes", description: "Océan traître où les tempêtes surgissent sans prévenir. Des épaves tapissent le fond." },
    { name: "Tortuga", description: "Port franc où règne la loi du plus fort. Tout se vend, tout s'achète, personne ne pose de questions." },
    { name: "Grotte aux Mille Échos", description: "Cavernes marines où les voix portent à des kilomètres. Les pirates y cachent leur butin." },
    { name: "Le Repaire des Flibustiers", description: "Forteresse naturelle cachée dans une crique. Bastion des pirates les plus redoutés." },
    { name: "Baie des Noyés", description: "Cimetière de navires où les courants ramènent les épaves. Des âmes errantes y pleurent." },
    { name: "Citadelle de la Couronne", description: "Forteresse royale imprenable gardant l'entrée du port. Ses canons dominent la rade." },
    { name: "L'Île aux Perles", description: "Lagon paradisiaque protégé par une tribu guerrière. Les perles noires y sont légendaires." },
    { name: "Marché aux Esclaves de Zanzibar", description: "Bazar bruyant où se négocient marchandises, informations et vies humaines." },
    { name: "Le Gouffre du Diable", description: "Tourbillon géant qui avale les navires imprudents. Une légende dit qu'il mène à un monde sous-marin." },
    { name: "Fort-de-la-Mort", description: "Prison imprenable creusée dans la falaise. Personne ne s'en est jamais échappé." },
  ],
  npcs: [
    { name: "Barbe-Grise", role: "vieux loup de mer", description: "Pirate à la retraite, il connaît chaque crique et chaque légende des Caraïbes." },
    { name: "Mira la Rouge", role: "corsaire légendaire", description: "Capitaine impitoyable au chapeau à plume rouge. Sa réputation dépasse sa flotte." },
    { name: "Capitaine Corbeau", role: "chasseur de primes", description: "Ancien pirate devenu traqueur. Il connaît toutes les cachettes des hors-la-loi." },
    { name: "Ti-Jean le Mapuche", role: "navigateur", description: "Cannibale repenti devenu navigateur. Il lit dans les étoiles comme dans un livre." },
    { name: "Docteur Savannah", role: "chirurgien de bord", description: "Femme mystérieuse qui soigne les pirates avec des plantes rares et des remèdes vaudous." },
    { name: "Le Perroquet Savant", role: "espion à plumes", description: "Perroquet capable de répéter des conversations entières. Très recherché." },
    { name: "Amiral Morgan", role: "chasseur de pirates", description: "Officier de la marine royale, obsédé par l'éradication de la piraterie." },
    { name: "Séréna des Vagues", role: "sirène rebelle", description: "Créature mi-femme mi-poisson, elle guide les pirates à travers les récifs." },
    { name: "Jacques le Borgne", role: "canonnier", description: "Il a perdu un œil en manipulant un canon. Son visage raconte cent batailles navales." },
    { name: "Comtesse de la Mer", role: "noble pirate", description: "Aristocrate déchue devenue pirate. Ses manières raffinées cachent une dureté implacable." },
  ],
  earlyEvents: [
    { text: "Un tonneau de rhum flotte à la dérive. À l'intérieur, un message et une montre à gousset en or.", consequence: "Le message contient la première piste vers un trésor légendaire." },
    { text: "Une tavernière vous glisse une clé rouillée : 'La chambre du fond. Quelqu'un vous attend.'", consequence: "Dans la chambre, un vieux pirate vous confie une mission périlleuse." },
    { text: "Un marin ivre vous provoque en duel. Le vainqueur hérite de sa carte au trésor.", consequence: "La carte est déchirée. L'autre moitié est chez le gouverneur." },
    { text: "Le navire royal vous prend en chasse. Vous devez trouver un abri ou vous cacher.", consequence: "Semer le navire royal vous oblige à traverser des eaux dangereuses." },
    { text: "Un naufragé est repêché. Il délire à propos d'une cité d'or cachée dans la jungle.", consequence: "En reprenant ses esprits, il révèle les coordonnées de la cité perdue." },
    { text: "Des dauphins guident votre navire vers une crique cachée. Une grotte ornée de peintures anciennes s'y trouve.", consequence: "Les peintures racontent l'histoire d'un trésor maudit." },
    { text: "Un marchand d'esclaves propose un marché : un membre d'équipage contre un coffre rempli d'armes.", consequence: "Le marchand cache ses vraies intentions. Il veut infiltrer votre équipage." },
    { text: "La provision d'eau douce a été empoisonnée. Un membre d'équipage est mort.", consequence: "Le coupable est à bord. La paranoïa s'installe parmi les pirates." },
    { text: "Un navire marchand isolé est repéré à l'horizon. Ses cales semblent pleines.", consequence: "L'abordage est risqué : le navire pourrait être un piège de la marine." },
    { text: "Une tempête éclate soudainement. Les vagues menacent de briser le navire.", consequence: "Survivre à la tempête renforce la confiance de l'équipage en vous." },
    { text: "Un requin géant suit le navire depuis des jours. L'équipage est superstitieux.", consequence: "Le requin est un présage. Les anciens disent qu'il guide vers un trésor." },
    { text: "Vous découvrez un stowaway — un enfant caché dans la cale. Il dit pouvoir parler aux animaux marins.", consequence: "L'enfant est recherché par l'Inquisition pour sorcellerie." },
  ],
  midEvents: [
    { text: "Un navire de guerre royal vous prend en tenaille. Le combat est inévitable.", consequence: "La bataille navale décidera de votre liberté ou de votre capture." },
    { text: "Un équipage rival pirate vos propres réserves pendant la nuit. La trahison est proche.", consequence: "Un traître est parmi vous. Les soupçons divisent l'équipage." },
    { text: "La mutinerie gronde. Une partie de l'équipage veut destituer le capitaine.", consequence: "Vous devez choisir votre camp : l'autorité ou la révolte." },
    { text: "Une île volcanique entre en éruption. La lave menace d'engloutir un village côtier.", consequence: "Les villageois vous supplient de les évacuer. La mer devient dangereuse." },
    { text: "Un kraken attaque le navire. Ses tentacules brisent le mât principal.", consequence: "Combattre le kraken ou fuir ? Chaque choix a un prix." },
    { text: "Une carte mystérieuse menant à un trésor est découverte dans un vieux grimoire.", consequence: "La carte est codée. La déchiffrer mène à une île qui ne figure sur aucune mappemonde." },
    { text: "Les morts-vivants d'un navire fantôme montent à l'abordage. Leur capitaine était un pirate légendaire.", consequence: "Le capitaine fantôme cherche son trésor perdu et une âme à emporter." },
    { text: "Un ouragan force le navire à s'échouer sur une île déserte. Les provisions sont perdues.", consequence: "Survivre sur l'île nécessite de trouver eau, nourriture et un moyen de repartir." },
    { text: "Une flibustière célèbre vous propose une alliance. Elle cache une attirance dangereuse.", consequence: "L'alliance apporte puissance et ennemis. Et peut-être un amour interdit." },
    { text: "Le gouverneur capture votre équipage. Il propose un échange : le trésor ou leurs vies.", consequence: "Vous devez infiltrer le fort royal pour libérer vos hommes." },
    { text: "Un vaisseau négrier est abordé. Les esclaves libérés veulent se joindre à vous.", consequence: "Libérer les esclaves fait de vous une cible pour les chasseurs de primes." },
    { text: "Un trésor maudit trouvé dans une épave apporte la malchance à l'équipage. Les accidents se multiplient.", consequence: "La malédiction ne se dissipe qu'en rendant le trésor à son propriétaire légitime." },
  ],
  climaxEvents: [
    { text: "Le trésor légendaire est à portée de main, mais gardé par un ennemi juré. Le combat final décide de tout.", consequence: "L'or ou la vengeance. Le choix vous définira pour toujours." },
    { text: "La flotte royale encercle votre repaire. La dernière bataille est imminente.", consequence: "Une issue héroïque ou une mort de pirate. La légende s'écrit maintenant." },
    { text: "Le trésor n'existe pas. Tout était un piège du gouverneur pour capturer tous les pirates en un seul endroit.", consequence: "La trahison était orchestrée depuis le début. Votre seul choix est le combat ou la fuite." },
    { text: "Le kraken légendaire émerge des profondeurs pour défendre le trésor. La mer bouillonne.", consequence: "Affronter le kraken : le combat le plus périlleux de votre vie de pirate." },
    { text: "La sirène que vous avez sauvée vous conduit à la cité engloutie. L'Atlantide existe vraiment.", consequence: "Explorer l'Atlantide révèle des secrets qui changent le monde." },
    { text: "Votre ancien capitaine, que vous croyez mort, réapparaît pour réclamer le trésor et votre tête.", consequence: "Les fantômes du passé règlent leurs comptes. Un duel à mort s'impose." },
    { text: "L'amiral Morgan en personne monte à bord. Le duel décidera du sort des pirates des Caraïbes.", consequence: "Vaincre Morgan fait de vous la légende des mers. Perdre signifie la prison à vie." },
    { text: "Le trésor maudit s'anime. Les pièces d'or forment un golem de métal fondu.", consequence: "Le golem d'or est invincible tant que les pièces restent ensemble." },
  ],
  twists: [
    "Le trésor que vous cherchez a déjà été trouvé par votre propre capitaine, qui vous mène en bateau.",
    "La carte au trésor est en réalité un piège de la marine royale pour capturer tout l'équipage.",
    "Le kraken n'est pas un monstre mais le gardien d'un passage vers un nouveau monde.",
    "Votre meilleur ami est un agent de la couronne infiltré depuis des années.",
    "La sirène qui vous guide cherche en réalité à vous noyer pour rejoindre son royaume sous-marin.",
    "L'île au trésor est volcanique et sur le point d'entrer en éruption. La lave détruira tout.",
    "Le galion fantôme est votre propre navire du futur, venu vous avertir d'une catastrophe.",
  ],
  endings: [
    { text: "Vous devenez le roi des pirates, rassemblant les flibustiers sous un seul pavillon.", condition: "De simple pirate, vous êtes devenu une légende. Les océans vous appartiennent et votre nom inspire crainte et respect." },
    { text: "Le trésor est à vous. Vous vous retirez sur une île paradisiaque pour une vie de luxe et de paix.", condition: "Les poches pleines d'or, vous coulez des jours heureux au soleil. Jusqu'à la prochaine aventure..." },
    { text: "Vous pardonnez au gouverneur et devenez corsaire au service de la couronne.", condition: "L'amnistie signée, vous combattez désormais pour la justice. Mais la nostalgie du pavillon noir vous rattrape parfois." },
    { text: "Le trésor était maudit. Vous le jetez dans le gouffre du diable pour sauver vos hommes.", condition: "Richesse ou honneur ? Vous avez choisi la vie de votre équipage. Leur loyauté vous est acquise à jamais." },
    { text: "Vous coulez avec votre navire, refusant d'abandonner votre équipage.", condition: "Les anciens disent que votre fantôme veille encore sur les mers, protégeant les marins perdus." },
    { text: "Vous prenez la tête d'une colonie pirate libre, fondant une république sans roi ni maître.", condition: "Votre république pirate devient un phare de liberté. Les opprimés du monde entier y trouvent refuge." },
    { text: "L'Atlantide vous offre l'immortalité. Vous devenez le gardien éternel de la cité engloutie.", condition: "Vous ne reverrez jamais la surface. Mais vous avez trouvé la paix dans les profondeurs." },
  ],
  choiceSets: [
    ["Aborder le navire", "Canonner à distance", "Parlementer"],
    ["Suivre la carte au trésor", "Explorer l'île voisine", "Rallier Tortuga"],
    ["Recruter plus d'hommes", "Faire des réparations", "Charger les canons"],
    ["Négocier avec le gouverneur", "Attaquer le fort", "Contourner le blocus"],
    ["Partager le butin", "Garder le trésor", "Investir dans un nouveau navire"],
    ["Faire confiance à l'équipage", "Renforcer la discipline", "Jouer la carte de la peur"],
    ["Plonger sous l'eau", "Attendre en surface", "Tendre une corde"],
    ["Brasero et fumée", "Drapeau de trêve", "Tirs de semonce"],
  ],
  artifacts: [
    { name: "Boussole des Âmes", description: "Ne pointe pas vers le nord, mais vers ce que vous désirez le plus au monde." },
    { name: "Sabre du Soleil Noir", description: "Lame forgée dans un météorite. Elle ne rouille jamais et tranche l'acier." },
    { name: "Compas du Temps", description: "Permet de voir les événements qui se sont déroulés à un endroit précis." },
    { name: "Cartes du Diable", description: "Jeu de cartes qui prédit l'avenir. Chaque tirage révèle un destin possible." },
    { name: "Pierre de Lune", description: "Gemme qui éclaire sous l'eau et repousse les créatures des abysses." },
    { name: "Cor de Brume", description: "Cor en nacre qui invoque une brume épaisse pour couvrir votre fuite." },
    { name: "Ancre Maudite", description: "Ancre qui empêche un navire de couler, même gravement endommagé." },
    { name: "Fiole du Vent", description: "Remplie de l'air d'une tempête. Libérée, elle crée une rafale dévastatrice." },
  ],
  monsters: [
    "un Kraken aux tentacules gigantesques",
    "une Sirène enchanteresse",
    "un Léviathan des profondeurs",
    "une Meute de requins affamés",
    "un Calmar géant",
    "un Dragon des mers",
    "un Serpent de mer à trois têtes",
    "des Pirates zombies émergeant des flots",
    "une Méduse lumineuse mortelle",
    "un Hippocampe géant",
  ],
};
