import type { GenreContent } from "./types";

export const ROMANCE_CONTENT: GenreContent = {
  plotHooks: [
    "Vous héritez d'une librairie ancienne dans un village côtier. Le notaire est mystérieusement séduisant.",
    "Une lettre d'amour perdue depuis 50 ans refait surface, menaçant de révéler un secret de famille.",
    "Vous êtes inscrit contre votre gré à un stage de reconnexion dans un château perdu.",
    "Un inconnu vous sauve la vie dans une rue déserte. Le lendemain, c'est votre nouveau collègue.",
    "Votre meilleur ami se marie. Vous êtes témoin. L'autre témoin est votre ex.", 
    "Une tempête de neige vous bloque dans un chalet avec un parfait inconnu.",
    "Vous gagnez un concours de pâtisserie dont le prix est un dîner avec le juge.",
    "Un tableau dans une galerie d'art représente un lieu dont vous rêvez chaque nuit.",
  ],
  locations: [
    { name: "Café des Rêves", description: "Petit café parisien aux murs tapissés de livres. Le café y est toujours parfait." },
    { name: "Jardin des Lumières", description: "Parc botanique illuminé la nuit de mille lanternes. Les allées invitent à la promenade." },
    { name: "Plage du Crépuscule", description: "Crique isolée où le soleil couchant peint l'océan de couleurs flamboyantes." },
    { name: "Château de Valmont", description: "Bâtisse centenaire aux jardins à la française. Chaque pièce raconte une histoire d'amour." },
    { name: "Librairie L'Envolée", description: "Antre de livres anciens où le temps s'arrête. L'odeur du papier et de l'encre enveloppe tout." },
    { name: "Pont des Soupirs", description: "Pont de pierre surplombant une rivière scintillante. Lieu de rendez-vous secrets." },
    { name: "Marché aux Fleurs", description: "Étalages colorés embaumant le jasmin et la rose. Un endroit où tout semble possible." },
    { name: "Théâtre de l'Opéra", description: "Salle majestueuse aux velours rouges. Les rencontres entre les actes sont légendaires." },
    { name: "Vignoble du Soleil Couchant", description: "Collines de vignes à perte de vue. La dégustation y est une expérience sensuelle." },
    { name: "Gare Saint-Lazare", description: "Grande gare animée où les destins se croisent dans un tourbillon de départs et de retrouvailles." },
    { name: "Atelier d'Artiste", description: "Loft lumineux aux toiles éparpillées. L'art y est une seconde langue." },
    { name: "Balcon sur la Ville", description: "Terrasse panoramique au sommet d'un immeuble. La ville s'étend comme un océan de lumières." },
  ],
  npcs: [
    { name: "Julien Delacroix", role: "libraire passionné", description: "Yeux noisette et sourire en coin. Ses mains sentent le papier et l'encre." },
    { name: "Camille Moreau", role: "artiste peintre", description: "Cheveux ébouriffés couverts de taches de peinture. Un regard qui traverse l'âme." },
    { name: "Élodie Beaumont", role: "propriétaire du café", description: "Sourire chaleureux et regard pétillant. Elle connaît tous ses clients par leur prénom." },
    { name: "Alexandre Lefèvre", role: "architecte", description: "Homme élégant aux mains calleuses. Il construit des ponts et des rêves." },
    { name: "Rose Montclaire", role: "musicienne", description: "Ses doigts dansent sur les touches du piano. La musique est sa véritable langue." },
    { name: "Thomas Delorme", role: "jardinier paysagiste", description: "Silhouette athlétique, mains dans la terre. Il parle aux plantes comme à des amies." },
    { name: "Manon Dubois", role: "écrivaine", description: "Toujours un carnet à la main. Elle observe le monde avec des yeux d'enfant." },
    { name: "Lucas Fontaine", role: "chef cuisinier", description: "Tablier toujours taché, passionné et colérique. Ses plats racontent des histoires." },
  ],
  earlyEvents: [
    { text: "Une pluie soudaine vous surprend. Vous trouvez refuge sous l'auvent d'une boutique, à côté d'un inconnu qui sourit.", consequence: "Partager ce moment crée une connexion inattendue." },
    { text: "Vous renversez votre café sur un inconnu. Il rit et commande deux nouveaux cafés.", consequence: "La maladresse devient une excuse pour faire connaissance." },
    { text: "Un livre tombe d'une étagère devant vous. Vous le ramassez en même temps qu'une autre personne.", consequence: "Vos doigts se touchent. Le livre parle de destin." },
    { text: "Vous recevez un message destiné à quelqu'un d'autre. La conversation qui s'ensuit est surprenante.", consequence: "Un simple message erreur peut changer une vie." },
    { text: "Un ami commun vous présente lors d'une soirée. L'alchimie est immédiate.", consequence: "Le regard échangé dure une seconde de trop." },
    { text: "Vous croisez le même regard plusieurs fois dans la journée. Le hasard n'existe peut-être pas.", consequence: "Chaque rencontre fortuite semble organisée par le destin." },
    { text: "Un parfum de fleur d'oranger vous attire vers un étal du marché. La personne derrière vous le respire aussi.", consequence: "Ce parfum deviendra le vôtre, désormais associé à ce souvenir." },
    { text: "Vous êtes invité à un mariage où vous ne connaissez personne. Un autre invité solitaire attire votre attention.", consequence: "Deux solitudes peuvent se rencontrer au milieu d'une fête." },
    { text: "Votre chanson préférée passe à la radio au moment où vous entrez dans un café. Le serveur la fredonne.", consequence: "La musique crée un pont entre deux inconnus." },
    { text: "Un chien vous suit jusqu'à un parc où son propriétaire vous attend, gêné.", consequence: "Parfois, les animaux sont de meilleurs entremetteurs que les humains." },
  ],
  midEvents: [
    { text: "Un secret du passé refait surface, menaçant la confiance que vous avez construite.", consequence: "La vérité blesse, mais le mensonge détruit. Le choix vous appartient." },
    { text: "Un ex revient, semant le doute dans votre relation naissante.", consequence: "Les fantômes du passé testent la force de vos sentiments." },
    { text: "Une opportunité professionnelle dans une autre ville vous oblige à faire un choix.", consequence: "L'amour et l'ambition s'affrontent. Les sacrifices sont inévitables." },
    { text: "Un malentendu provoque une dispute. Les mots dépassent vos pensées.", consequence: "Ce qui est dit dans la colère ne peut pas toujours être repris." },
    { text: "Votre famille désapprouve votre choix. La pression sociale devient difficile à ignorer.", consequence: "Les liens du sang et du cœur sont parfois en conflit." },
    { text: "Une maladie ou un accident remet tout en perspective.", consequence: "L'adversité révèle la véritable force des sentiments." },
    { text: "Un geste romantique inattendu vous touche profondément, mais son auteur n'est pas celui que vous pensiez.", consequence: "Les apparences sont parfois trompeuses en amour." },
    { text: "La jalousie s'immisce dans votre relation, révélant des insécurités profondes.", consequence: "La confiance est le pilier le plus fragile de l'amour." },
    { text: "Un voyage imprévu vous rapproche physiquement et émotionnellement.", consequence: "Les kilomètres partagés créent des souvenirs indélébiles." },
    { text: "Vous découvrez un talent caché chez l'autre qui change votre regard sur lui.", consequence: "On tombe amoureux plusieurs fois de la même personne." },
  ],
  climaxEvents: [
    { text: "La déclaration est imminente. Les mots sont sur vos lèvres, prêts à tout changer.", consequence: "Trois mots peuvent construire ou détruire un monde." },
    { text: "Vous devez choisir entre rester dans votre zone de confort ou tout quitter pour l'amour.", consequence: "Le grand saut est terrifiant. Mais ne pas sauter l'est encore plus." },
    { text: "L'être aimé est sur le point de partir. C'est votre dernière chance de tout lui dire.", consequence: "Les adieux peuvent devenir des commencements si on ose." },
    { text: "Une révélation bouleversante change tout ce que vous pensiez savoir sur votre histoire.", consequence: "La vérité, même douloureuse, est la seule fondation solide." },
    { text: "Le moment du pardon ou de la rupture est arrivé. Les ponts brûlent ou se reconstruisent.", consequence: "Chaque relation arrive à ce carrefour où tout se décide." },
    { text: "Une demande en marriage, une promesse ou un aveu. L'instant qui décide d'une vie.", consequence: "Les 'oui' les plus importants sont ceux qu'on prononce avec le cœur." },
    { text: "Le grand geste romantique : tout miser sur une seule carte, au risque de tout perdre.", consequence: "L'amour véritable exige le courage de se mettre à nu." },
  ],
  twists: [
    "L'être aimé cache un talent incroyable qu'il n'a jamais révélé par peur du jugement.",
    "Vous avez déjà croisé cette personne des années auparavant, mais aucun de vous ne s'en souvient. Jusqu'à aujourd'hui.",
    "Le 'hasard' qui vous a réunis était en réalité orchestré par un ami commun.",
    "La personne idéale n'est pas celle que vous poursuiviez, mais celle qui était toujours là.",
    "Un pacte secret conclu dans l'enfance refait surface et change la donne.",
    "L'histoire d'amour que vous vivez est en train d'être écrite par l'être aimé, qui est romancier.",
    "Vous découvrez que vous êtes liés par un événement tragique du passé que vous aviez refoulé.",
  ],
  endings: [
    { text: "Vous vous déclarez enfin. L'amour est partagé. Une nouvelle vie commence ensemble.", condition: "Les mots 'je t'aime' résonnent dans l'air comme une promesse. Vous vous embrassez sous les étoiles." },
    { text: "Vous choisissez de rester amis, mais les sentiments demeurent, silencieux et profonds.", condition: "Parfois, l'amour prend la forme de l'amitié. Vous cheminez côte à côte, sans jamais vous toucher." },
    { text: "Vous partez chacun de votre côté, mais le souvenir de cette rencontre vous transforme à jamais.", condition: "Certaines personnes traversent nos vies pour nous apprendre à aimer. Vous repartez grandi." },
    { text: "Après des années, vous vous retrouvez par hasard. Le temps n'a rien effacé.", condition: "Le destin vous accorde une seconde chance. Cette fois, vous ne laisserez rien passer." },
    { text: "Vous construisez ensemble un projet de vie, mêlant vos rêves et vos ambitions.", condition: "L'amour véritable est un partenariat. Vous bâtissez quelque chose qui vous dépasse." },
    { text: "Le grand amour n'était pas celui que vous attendiez. Mais il est là, différent, réel.", condition: "Parfois, l'amour arrive déguisé. Il faut apprendre à le reconnaître sous une forme inattendue." },
    { text: "Vous décidez de prendre du temps pour vous. Si c'est réel, il attendra.", condition: "L'amour n'est pas une course. Prendre du recul peut être la preuve ultime de maturité." },
  ],
  choiceSets: [
    ["Dire la vérité", "Garder le silence", "Changer de sujet"],
    ["Faire le premier pas", "Attendre le bon moment", "Envoyer un signe"],
    ["Inviter à un café", "Proposer une promenade", "Offrir un compliment"],
    ["Écouter votre cœur", "Suivre la raison", "Demander conseil"],
    ["Envoyer un message", "Appeler", "Faire une surprise"],
    ["Vous ouvrir complètement", "Reservoir vos sentiments", "Partager un secret"],
    ["Planifier un rendez-vous", "Laisser faire le hasard", "Créer une occasion"],
    ["Danser avec lui/elle", "Parler toute la nuit", "Regarder les étoiles"],
    ["Offrir un cadeau", "Écrire une lettre", "Préparer un dîner"],
    ["Prendre sa main", "L'embrasser", "Murmurer un secret"],
  ],
  artifacts: [
    { name: "Médaillon Ancien", description: "Contient deux photos. L'une est la vôtre, l'autre est vide." },
    { name: "Journal Intime Bleu", description: "Relié en cuir, il semble avoir été écrit par quelqu'un qui vous connaît." },
    { name: "Bague de Famille", description: "Bijou ancien transmis depuis trois générations. Il porterait chance en amour." },
    { name: "Lettre Sans Nom", description: "Lettre d'amour trouvée dans un livre. Le destinataire est inconnu." },
    { name: "Boîte à Musique", description: "Sa mélodie évoque un souvenir d'enfance. Elle ne s'ouvre que la nuit." },
    { name: "Carnet de Voyage", description: "Pages remplies de dessins de lieux que vous avez visités sans le savoir." },
    { name: "Portrait au Pastel", description: "Esquisse d'un visage familier sans que vous sachiez où vous l'avez vu." },
  ],
  monsters: [],
};
