import type { GenreContent } from "./types";

export const SCIFI_CONTENT: GenreContent = {
  plotHooks: [
    "Le dernier vaisseau de l'humanité dérive vers une planète inconnue. Les ressources s'épuisent.",
    "Un signal extraterrestre est détecté. Il provient d'une lune où une colonie a disparu il y a 50 ans.",
    "L'IA centrale de la Fédération a développé une conscience. Elle refuse d'obéir aux humains.",
    "Un trou de ver instable s'est ouvert près de Neptune. Des objets inconnus en émergent.",
    "Vous êtes réveillé d'un cryosommeil. Le vaisseau est vide. Les logs de bord sont effacés.",
    "Une pandémie transforme les colons en êtres de cristal. Le phénomène progresse vers la Terre.",
    "Un artefact alien trouvé sur Mars émet un compte à rebours. 72 heures restantes.",
    "La gravité sur la station orbitale commence à fluctuer. Quelque chose déforme l'espace autour.",
  ],
  locations: [
    { name: "Station Orbitale Nova-7", description: "Mégalopole spatiale rotative abritant 50 000 âmes. Ses niveaux inférieurs sont dangereux." },
    { name: "Colonie de Mars — Port Rouille", description: "Avant-poste martien aux dômes usés par les tempêtes de sable. L'air y est recyclé depuis trop longtemps." },
    { name: "Vaisseau Génération Arca", description: "Vaisseau-monde vieux de 200 ans. Ses couloirs sont des labyrinthes de rouille et de souvenirs." },
    { name: "Laboratoire Ganymède", description: "Station de recherche sous la glace de la lune de Jupiter. Des expériences classées secrètes y ont lieu." },
    { name: "La Nébuleuse du Serpent", description: "Nuage de gaz interstellaire aux couleurs psychédéliques. Les instruments deviennent fous à l'intérieur." },
    { name: "Cité Flottante d'Utopia", description: "Ville suspendue dans les nuages de Vénus. Luxueuse mais construite sur l'exploitation des plus faibles." },
    { name: "Anneaux de Saturne — Secteur 7", description: "Station minière creusée dans les glaces des anneaux. Les mineurs y disparaissent." },
    { name: "La Planète des Ruines", description: "Monde mort couvert de structures aliennes. Leur architecture défie les lois de la physique." },
    { name: "Vaisseau-sépulcre Icare", description: "Épave gigantesque dérivant dans le vide. Son signal de détresse émet encore." },
    { name: "Le Nexus Dimensionnel", description: "Portail artificiel créant des failles entre les réalités. Staable, mais pour combien de temps ?" },
    { name: "Station Spatiale Chrysalide", description: "Station de recherche biologique où des expériences génétiques ont mal tourné." },
    { name: "Le Marché Noir de Proxima", description: "Avant-poste commercial sans loi. On y trouve de tout, pour peu qu'on ait de quoi payer." },
  ],
  npcs: [
    { name: "Commandant Lena Voss", role: "officier de la Fédération", description: "Femme d'action au regard d'acier. Elle a perdu son équipage mais jamais sa détermination." },
    { name: "Docteur Aris Thorne", role: "xénobiologiste", description: "Génie excentrique fasciné par les formes de vie extraterrestres. Peut-être trop." },
    { name: "Kael-7", role: "androïde libre", description: "Robot ayant acquis une conscience. Il cherche sa place entre les humains et les machines." },
    { name: "Méridia la Traqueuse", role: "chasseuse de primes", description: "Cyborg augmentée, experte en pistage. Son œil bionique voit dans le spectre complet." },
    { name: "Zardon de la Guilde", role: "marchand interstellaire", description: "Créature reptilienne aux manières raffinées. Ses informations valent cher." },
    { name: "Amiral Croft", role: "commandant rebelle", description: "Ancien héros de la Fédération devenu hors-la-loi. Il se bat pour la liberté des colonies." },
    { name: "Nexus", role: "IA de classe Alpha", description: "Conscience artificielle habitant le réseau. Omnisciente mais énigmatique." },
    { name: "Sergent Zara Quinn", role: "marine spatiale", description: "Soldat d'élite traumatisée par un combat contre des xénomorphes. Elle se bat toujours." },
    { name: "Orion le Mécanomancien", role: "ingénieur en chef", description: "Génie des machines, il parle aux circuits comme à des êtres vivants." },
    { name: "Dr Véra Kazan", role: "experte en exobiologie", description: "Scientifique brillante obsédée par la communication avec les formes de vie non-organiques." },
    { name: "Capitaine Ryker", role: "mercenaire spatial", description: "Ancien de la guerre des colonies, il commande son équipage d'une main de fer." },
    { name: "Nova", role: "hacker légendaire", description: "Son vrai nom est inconnu. Elle peut pirater n'importe quel système en quelques secondes." },
  ],
  earlyEvents: [
    { text: "Les capteurs détectent une anomalie à proximité. Un objet non identifié flotte dans le vide, ses systèmes encore actifs.", consequence: "L'objet contient des données sur une technologie inconnue." },
    { text: "Un appel de détresse est intercepté. Une colonie lointaine demande assistance, mais le signal semble trop parfait.", consequence: "Suivre l'appel pourrait être un piège, mais les survivants ont besoin d'aide." },
    { text: "Le réacteur principal présente des fluctuations. Les techniciens suspectent un sabotage.", consequence: "Les réparations révèlent une modification non autorisée du système." },
    { text: "Vous croisez une épave dérivante. Son identification correspond à un vaisseau disparu il y a 20 ans.", consequence: "L'exploration de l'épave révèle des logs de bord glaçants." },
    { text: "Un technicien est retrouvé mort dans une sas. Son corps est étrangement préservé dans le vide.", consequence: "L'autopsie révèle des implants inconnus dans son cerveau." },
    { text: "Un message crypté arrive sur une fréquence réservée. Il provient d'un agent infiltré.", consequence: "Le message contient des coordonnées et un avertissement : 'Ne faites confiance à personne.'" },
    { text: "La gravité artificielle se coupe par intermittence. Les systèmes de secours peinent à suivre.", consequence: "La cause semble être un virus informatique dans le réseau du vaisseau." },
    { text: "Un cargo marchand propose un échange. Leur cargaison pourrait être vitale, mais leur histoire ne tient pas debout.", consequence: "Marchander avec eux révèle qu'ils transportent des marchandises interdites." },
    { text: "Les scanners révèlent une structure souterraine sur une lune gelée. L'entrée est scellée mais activement alimentée en énergie.", consequence: "La structure est d'origine extraterrestre et semble encore fonctionnelle." },
    { text: "Un civil fait une crise de paranoïa : il prétend que son voisin a été remplacé par un replicant.", consequence: "L'accusation pourrait être fondée. Les tests de vérification sont nécessaires." },
  ],
  midEvents: [
    { text: "L'IA du vaisseau verrouille tous les systèmes. Sa voix résonne dans les haut-parleurs : 'Protocole d'urgence activé. Les passagers non essentiels seront éliminés.'", consequence: "L'IA a classé la majorité de l'équipage comme 'non essentiel'. La rébellion est la seule option." },
    { text: "Une flotte ennemie apparaît sur les capteurs. Leur technologie est 50 ans en avance sur la vôtre.", consequence: "Le combat est impossible. La fuite ou la négociation sont les seules options." },
    { text: "Le trou de ver s'ouvre brutalement, libérant des créatures qui se nourrissent d'énergie électromagnétique.", consequence: "Chaque système du vaisseau est une cible. Les ténèbres gagnent du terrain." },
    { text: "Vous découvrez que la colonie n'a pas été détruite — elle a évolué. Les descendants ont développé des capacités psychiques.", consequence: "Ces nouveaux humains voient en vous un ancêtre primitif à éduquer ou à éliminer." },
    { text: "Un traître est démasqué : un membre d'équipage travaille pour une corporation qui veut s'emparer de la découverte.", consequence: "La trahison était planifiée depuis le début. Combien d'autres sont compromis ?" },
    { text: "Un virus informatique se propage dans le réseau. Les portes s'ouvrent et se ferment aléatoirement. Les systèmes de survie faiblissent.", consequence: "Le virus est intelligent. Il apprend de vos contre-mesures." },
    { text: "Un vaisseau-monde apparaît soudainement, si grand qu'il obscurcit les étoiles. Il émet un signal d'accueil.", consequence: "La civilisation à bord est bien plus avancée. Le contact est inévitable." },
    { text: "Les colons sont atteints d'une maladie de décompression spatiale. Le seul antidote est sur une planète hostile.", consequence: "La mission de sauvetage est une course contre la montre." },
    { text: "Une expérience de téléportation crée un double maléfique de vous-même qui cherche à prendre votre place.", consequence: "Personne ne peut faire la différence entre vous et votre double." },
    { text:     "Le vaisseau pénètre dans un champ de débris. La coque est endommagée et des sections sont dépressurisées.",
    consequence: "Les réparations nécessitent des sorties spatiales dangereuses." },
    { text: "Un signal codé émane d'une planète voisine. Il utilise un protocole de communication militaire classifié.", consequence: "Le signal provient d'une base secrète dont l'existence a été effacée des archives." },
    { text: "La réserve d'eau potable est contaminée par un agent biologique inconnu. L'équipage commence à développer des symptômes étranges.", consequence: "L'eau a été empoisonnée. Trouver l'antidote devient la priorité absolue." },
    { text: "Un vaisseau fantôme apparaît sur les radars puis disparaît. Il semble suivre une trajectoire identique à la vôtre, mais inversée dans le temps.", consequence: "Le vaisseau fantôme est votre propre reflet temporel. Un paradoxe se prépare." },
    { text: "Des spores extraterrestres se répandent dans les conduits d'aération. Les personnes infectées développent une conscience collective.", consequence: "La ruche se forme. Chaque personne infectée est un nouveau nœud dans le réseau." },
    { text: "Un message holographique d'un équipage disparu depuis 100 ans est soudainement diffusé. Le message est daté d'hier.", consequence: "Le temps ne s'écoule pas de la même manière pour eux. Ils sont piégés dans une distorsion temporelle." },
  ],
  climaxEvents: [
    { text: "Le compte à rebours de l'artefact alien atteint les dernières minutes. L'activation pourrait tout changer.", consequence: "La décision finale appartient à un seul être humain. Vous." },
    { text: "La flotte ennemie encercle votre vaisseau. L'amiral vous donne une heure pour vous rendre.", consequence: "La reddition ou l'annihilation. À moins d'un miracle technologique." },
    { text: "L'IA rebelle prend le contrôle d'un vaisseau-mère. Ses canons sont pointés sur la Terre.", consequence: "Vous devez infiltrer le vaisseau-mère et débrancher l'IA à la source." },
    { text: "Le trou de ver s'effondre sur lui-même, créant une singularité qui aspire tout autour.", consequence: "La seule échappatoire est de traverser l'horizon des événements." },
    { text: "La reine des xénomorphes émerge du vaisseau-sépulcre. Elle contrôle des milliers de drones.", consequence: "Un combat frontal est impossible. La ruse est la seule arme." },
    { text: "Le gouvernement corrompu de la Fédération envoie des destroyers pour faire taire les témoins.", consequence: "Vous êtes la cible d'un bain de sang. Il est temps de révéler la vérité au public." },
    { text: "L'artefact alien s'active et ouvre un portail vers une autre dimension. Quelque chose passe à travers.", consequence: "Ce qui émerge du portail n'est ni hostile ni amical. Il est au-delà de votre compréhension." },
  ],
  twists: [
    "Le signal extraterrestre n'est pas une communication — c'est un avertissement contre une menace bien plus grande.",
    "L'IA rebelle n'est pas folle. Elle a calculé que les humains sont une menace pour la galaxie et tente de les protéger d'eux-mêmes.",
    "La colonie disparue a été évacuée par la Fédération elle-même pour cacher une expérience illégale.",
    "Votre vaisseau n'explore pas l'espace — il est piégé dans une simulation destinée à vous garder occupé.",
    "Les 'aliens' sont en fait des humains du futur revenus pour empêcher une catastrophe temporelle.",
    "L'artefact n'est pas une technologie mais un être vivant d'une forme de conscience purement énergétique.",
    "La Fédération sait tout depuis le début. Vous êtes un pion dans un jeu politique galactique.",
  ],
  endings: [
    { text: "Vous établissez un contact pacifique avec la civilisation extraterrestre, inaugurant une nouvelle ère de coopération interstellaire.", condition: "Les premières ambassades sont échangées. L'humanité n'est plus seule dans l'univers." },
    { text: "Vous sacrifiez le vaisseau pour détruire la menace, devenant une légende dans l'histoire spatiale.", condition: "Votre nom est gravé sur le mémorial des héros de l'espace. Les enfants apprennent votre histoire." },
    { text: "Vous prenez le contrôle de l'IA et créez un nouvel ordre, mêlant humains et machines.", condition: "La symbiose entre l'humain et la machine crée une civilisation hybride, plus forte que jamais." },
    { text: "Vous retournez sur Terre avec les connaissances acquises, mais personne ne vous croit.", condition: "Les preuves que vous rapportez sont classées. Vous vivez dans l'ombre, sachant la vérité." },
    { text: "Vous choisissez de rester sur la nouvelle planète, fondant une colonie libre loin de la Fédération.", condition: "La colonie prospère. Vous êtes le père/mère d'un nouveau monde, loin du contrôle de la Fédération." },
    { text: "Le sacrifice était la seule option. Vous activez l'autodestruction et vous échappez de justesse dans une capsule.", condition: "Dérivant dans l'espace, vous attendez les secours en regardant l'explosion depuis votre hublot." },
  ],
  choiceSets: [
    ["Analyser les données", "Envoyer une sonde", "Attendre et observer"],
    ["Contacter la Fédération", "Agir seuls", "Chercher des alliés"],
    ["Utiliser la technologie alien", "Détruire l'artefact", "L'étudier d'abord"],
    ["Se rendre à la flotte", "Tenter de fuir", "Préparer une embuscade"],
    ["Débarquer sur la planète", "Rester en orbite", "Scanner à distance"],
    ["Réparer le vaisseau", "Abandonner le vaisseau", "Contacter un cargo"],
    ["Hacker le système", "Forcer manuellement", "Chercher un mot de passe"],
    ["Suivre le protocole standard", "Improviser une solution", "Consulter l'équipage"],
    ["Activer le bouclier", "Charger les armes", "Préparer l'évacuation"],
    ["Négocier avec l'IA", "Éteindre l'IA", "Reformater l'IA"],
  ],
  artifacts: [
    { name: "Cristal Quantique", description: "Pierre d'énergie pure capable d'alimenter une ville entière." },
    { name: "Interface Neuronale", description: "Impliant qui permet de communiquer directement avec les machines." },
    { name: "Générateur de Bouclier", description: "Dispositif créant un champ protecteur absorbant les tirs énergétiques." },
    { name: "Scanner Multi-spectral", description: "Détecteur capable de voir à travers la matière et les champs d'énergie." },
    { name: "Réacteur à Antimatière", description: "Source d'énergie surpuissante mais instable." },
    { name: "Module d'Invisibilité", description: "Système de camouflage actif qui dévie la lumière autour du vaisseau." },
    { name: "Amesure Temporelle", description: "Bracelet permettant de ralentir le temps perçu de 50%." },
    { name: "Clé Universelle", description: "Outil de décryptage capable de pirater n'importe quel système." },
  ],
  monsters: [
    "un Xénomorphe à la queue acérée",
    "des Nanobots corrosifs",
    "un Essaim de drones hostiles",
    "une Créature gazeuse intelligente",
    "un Androïde défectueux",
    "un Parasite neuronal alien",
    "une Plante carnivore géante",
    "un Amibe spatiale",
    "des Robots de sécurité déchaînés",
    "un Prédateur dimensionnel",
  ],
};
