import type { GenreContent } from "./types";

export const WESTERN_CONTENT: GenreContent = {
  plotHooks: [
    "Un shérif corrompu a pris le contrôle de la ville. Personne n'ose se dresser contre lui.",
    "Une rançon est exigée pour libérer le médecin du village. Vous devez réunir la somme avant la pendaison.",
    "Le train transportant l'or de la banque fédérale sera attaqué. Vous pouvez le défendre ou le dévaliser.",
    "Une mystérieuse étrangère arrive en ville avec une prime sur sa tête et des secrets dangereux.",
    "Votre ranch est menacé par un baron du bétail qui veut s'emparer des terres.",
    "Un hors-la-loi que vous croyez mort refait surface. Il veut régler ses comptes.",
    "Une mine d'argent a été découverte. Tout le monde veut sa part, y compris les bandits mexicains.",
    "La diligence transportant des médicaments vitaux a disparu dans le désert.",
  ],
  locations: [
    { name: "Redemption", description: "Ville poussiéreuse au cœur du désert. Saloon, banque, église et prison se côtoient sur Main Street." },
    { name: "Canyon du Diable", description: "Gorges rouges et escarpées où les bandits tendent des embuscades. Les os blanchis tapissent le sol." },
    { name: "Ranch du Soleil Couchant", description: "Grand ranch entouré de barbelés. Le bétail s'étend à perte de vue." },
    { name: "Saloon du Coyote", description: "Repaire des chercheurs d'or et des joueurs de poker. L'odeur du whisky et du tabac imprègne les murs." },
    { name: "Fort Independence", description: "Avant-poste de la cavalerie américaine. Les soldats y surveillent les territoires indiens." },
    { name: "Village Fantôme de Dry Gulch", description: "Cité abandonnée après une épidémie de fièvre de l'or. Les portes claquent dans le vent." },
    { name: "La Piste de Santa Fe", description: "Route poussiéreuse reliant les comptoirs commerciaux. Les diligences y sont souvent attaquées." },
    { name: "Mine du Pic Mort", description: "Mine d'argent aux tunnels instables. Des mineurs y disparaissent régulièrement." },
    { name: "Territoire Apache", description: "Terres sacrées des peuples natifs. Les colons y pénètrent à leurs risques et périls." },
    { name: "Gare de la Frontière", description: "Petite gare en bois où passe le train transcontinental. Point de départ vers l'ouest." },
    { name: "Bureau du Shérif", description: "Bâtiment à l'étoile rouillée. La prison au sous-sol n'a jamais réussi à retenir les pires bandits." },
    { name: "Lac Salé", description: "Étendue d'eau amère au milieu du désert. Légendes et mirages hantent ses rives." },
  ],
  npcs: [
    { name: "Shérif Dan Cooper", role: "homme de loi intègre", description: "Homme mûr à la moustache grise, il fait régner l'ordre à Redemption depuis 20 ans." },
    { name: "Belle LaRose", role: "tenancière du saloon", description: "Femme d'affaires redoutable sous ses jupons. Elle sait tout ce qui se passe en ville." },
    { name: "Jesse l'Éclaireur", role: "chasseur de primes", description: "Homme silencieux au chapeau usé. Il traque les hors-la-loi pour l'argent, pas pour la justice." },
    { name: "Docteur Samuel Wells", role: "médecin de campagne", description: "Ancien alcoolique devenu guérisseur. Il soigne aussi bien les balles que les cœurs brisés." },
    { name: "P'tit Loup", role: "guide Apache", description: "Guerrier apache qui connaît chaque cañon et chaque source du territoire." },
    { name: "Big Bill Jackson", role: "baron du bétail", description: "Homme obèse au cigare permanent. Il possède la moitié des terres et veut l'autre moitié." },
    { name: "Sœur Marie-Grâce", role: "missionnaire", description: "Nonne au cœur de lion, elle soigne les pauvres et tient tête aux bandits." },
    { name: "Johnny 'Doigts d'Argent'", role: "joueur professionnel", description: "Joueur de poker élégant au revolver toujours chargé. Il gagne ou il meurt." },
    { name: "Calamity Kate", role: "hors-la-loi", description: "Cavalière émérite au regard farouche. Sa tête est mise à prix 5000$." },
    { name: "Télégraphiste Morse", role: "agent fédéral", description: "Homme discret qui en sait long. Les dépêches qu'il reçoit décident du sort des hommes." },
  ],
  earlyEvents: [
    { text: "Un inconnu vous défie en duel devant le saloon. La foule se rassemble en cercle.", consequence: "Le duel est une tradition. Le vainqueur gagne le respect, le perdant gagne une balle." },
    { text: "Un cheval sans cavalier arrive au galop, les sangles tachées de sang.", consequence: "Le cavalier est blessé ou mort. Suivre la piste du cheval mène à une attaque de diligence." },
    { text: "Le télégraphe sonne : un message annonce que le juge arrivera dans trois jours.", consequence: "Le juge vient pendre un prisonnier. Certains veulent libérer le prisonnier avant." },
    { text: "Une tempête de sable se lève. Vous devez trouver un abri rapidement.", consequence: "Dans une grotte, vous découvrez des fresques indiennes et un coffre d'armes." },
    { text: "Un enfant vous montre une dent en or trouvée dans la rue. Elle vient de la mine.", consequence: "La mine est abandonnée mais quelqu'un y creuse en secret depuis peu." },
    { text: "Le shérif recrute des adjoints. Les bandits de la région préparent un mauvais coup.", consequence: "Devenir adjoint vous donne autorité et ennemis." },
    { text: "Un marchand ambulant vend des élixirs miracles. L'un d'eux contient de l'or véritable.", consequence: "L'élixir est une arnaque... ou peut-être pas. Le marchand cache quelque chose." },
    { text: "Un train siffle au loin. Le convoi mensuel d'or traverse la région.", consequence: "Le train d'or est une cible tentante pour tous les bandits des environs." },
    { text: "Un troupeau de bisons traverse la piste. La chasse est bonne mais dangereuse.", consequence: "Les peaux de bisons valent cher. Mais les chasseurs attirent les Indiens." },
    { text: "La diligence arrive avec un seul passager : un banquier de l'Est, nerveux et bien armé.", consequence: "Le banquier transporte des documents qui pourraient ruiner le baron du bétail." },
    { text: "Un feu de prairie se propage rapidement. Tout le monde forme une chaîne pour l'éteindre.", consequence: "L'incendie était criminel. Des traces de pétrole sont retrouvées." },
    { text: "Un homme enchaîné s'échappe de la prison. Le shérif offre 200$ à qui le rattrape.", consequence: "Le fugitif est innocent. Il a été accusé à tort par le baron du bétail." },
  ],
  midEvents: [
    { text: "Le baron du bétail envoie ses hommes de main pour vous chasser de vos terres.", consequence: "Les hommes de main brûlent votre grange. La guerre est déclarée." },
    { text: "Un gang de hors-la-loi prend la banque d'assaut. Des otages sont retenus.", consequence: "Les bandits sont retranchés. Négocier ou donner l'assaut ?" },
    { text: "La ville est divisée : les éleveurs contre les fermiers. La violence menace d'éclater.", consequence: "Les deux camps ont des raisons valables. Un compromis semble impossible." },
    { text: "Un shérif fédéral arrive pour enquêter sur les disparitions mystérieuses.", consequence: "Les disparitions sont liées à la mine. Quelqu'un cache des corps." },
    { text: "Une tribu apache attaque la diligence. Les survivants sont emmenés.", consequence: "Les Apaches protègent leurs terres. La négociation est préférable aux armes." },
    { text: "Le bétail est volé pendant la nuit. Les traces mènent vers le territoire mexicain.", consequence: "Récupérer le bétail nécessite une incursion risquée de l'autre côté de la frontière." },
    { text: "Un joueur de poker est accusé de triche. La foule veut le pendre sur place.", consequence: "Le joueur est innocent mais personne ne l'écoute. Vous devez agir vite." },
    { text: "L'eau du puits est empoisonnée. Les habitants tombent malades un par un.", consequence: "Le poison est dans la nappe phréatique. La source de contamination est à trouver." },
    { text: "Un prédicateur itinérant prêche la fin du monde. Les habitants sont terrifiés.", consequence: "Le prédicateur est un chercheur d'or qui veut éloigner les gens de la mine." },
    { text: "La diligence postale est retrouvée vide, les chevaux disparus.", consequence: "Le conducteur a abandonné la diligence. Il a été soudoyé." },
    { text: "Un convoi de la cavalerie traverse la ville. Ils cherchent un déserteur.", consequence: "Le déserteur est caché au saloon. Le livrer ou le protéger ?" },
    { text: "Une épidémie de fièvre jaune se déclare. Le docteur manque de médicaments.", consequence: "Les médicaments sont à la ville voisine, mais le chemin est dangereux." },
  ],
  climaxEvents: [
    { text: "Le baron du bétail et ses hommes encerclent la ville. Le duel final décide du sort de Redemption.", consequence: "Le combat dans les rues poussiéreuses entrera dans la légende de l'Ouest." },
    { text: "Le train d'or arrive. Tout le monde le veut : les bandits, le shérif, la banque.", consequence: "Le train est un piège. Le coffre est vide — c'est une opération du gouvernement fédéral." },
    { text: "Un duel en plein midi sur Main Street. Vous contre le tireur le plus rapide de l'Ouest.", consequence: "Dix pas. Trois secondes. Un seul survivra. La légende dit que le plus rapide gagne." },
    { text: "Les Apaches attaquent le fort. La cavalerie est en sous-nombre.", consequence: "Défendre le fort ou négocier la paix ? Chaque choix coûte des vies." },
    { text: "La mine s'effondre. Des mineurs sont piégés à l'intérieur. Le temps presse.", consequence: "Les sauver ou récupérer l'or ? La conscience ou la richesse ?" },
    { text: "Le gouverneur offre une amnistie aux hors-la-loi qui se rendent. Mais c'est un piège.", consequence: "Se rendre, c'est la prison à vie. Fuir, c'est être traqué pour toujours." },
    { text: "L'armée mexicaine traverse la frontière. La guerre entre les deux nations est imminente.", consequence: "Vous êtes au mauvais endroit au mauvais moment. Ou peut-être à l'endroit idéal pour faire la différence." },
  ],
  twists: [
    "Le shérif corrompu est en réalité un agent fédéral qui enquête sur le baron du bétail.",
    "Le hors-la-loi que vous traquez est votre propre fils que vous n'avez jamais connu.",
    "La mine d'argent est épuisée. Le baron du bétail répand la rumeur pour faire monter le prix des terres.",
    "Les Indiens ne sont pas les agresseurs — ils défendent leurs terres sacrées volées par le gouvernement.",
    "Le docteur est un ancien hors-la-loi qui a changé d'identité. Sa tête est toujours mise à prix.",
    "L'or du train est faux. C'est une opération secrète pour piéger les hors-la-loi.",
    "La femme mystérieuse est une détective privée de l'Est venue enquêter sur une série de meurtres.",
  ],
  endings: [
    { text: "Vous devenez le nouveau shérif de Redemption, ramenant la paix et la justice.", condition: "L'étoile brille sur votre poitrine. La ville vous respecte et les bandits vous craignent." },
    { text: "Vous prenez l'or et partez vers l'ouest, cherchant une nouvelle vie et une nouvelle chance.", condition: "Les poches pleines et le passé derrière vous, l'horizon vous appelle. L'Ouest est encore vaste." },
    { text: "Vous rendez les terres aux Apaches et devenez le pont entre deux mondes.", condition: "La paix entre colons et natifs est fragile mais réelle. Vous êtes l'artisan de cette réconciliation." },
    { text: "Vous vengez votre famille et brûlez le ranch du baron. La dette de sang est soldée.", condition: "La vengeance est un plat qui se mange froid. Mais le goût en est-il aussi doux que vous l'imaginiez ?" },
    { text: "Vous mourez les armes à la main, en héros. Votre nom est chanté dans tout l'Ouest.", condition: "Les balles ont emporté votre corps, mais votre esprit galope encore dans les plaines de l'Ouest." },
    { text: "Vous quittez la violence et devenez fermier, trouvant la paix dans la terre et le travail.", condition: "La charrue est plus lourde que le revolver, mais elle nourrit. Les champs sont votre nouveau combat." },
    { text: "Vous prenez la tête des hors-la-loi et devenez le bandit le plus célèbre du territoire.", condition: "Votre tête est mise à prix 10 000$. Chaque jour est une fuite, chaque nuit une survie." },
  ],
  choiceSets: [
    ["Dégainer votre revolver", "Parler calmement", "Appeler le shérif"],
    ["Monter à cheval et poursuivre", "Suivre les traces à pied", "Attendre au prochain relais"],
    ["Entrer dans le saloon", "Faire le tour par l'arrière", "Monter sur le toit"],
    ["Ouvrir le coffre-fort", "Brûler les papiers", "Prendre seulement l'or"],
    ["Négocier avec les bandits", "Donner l'assaut", "Les encercler"],
    ["Suivre la piste à cheval", "Prendre la diligence", "Voyager de nuit"],
    ["Acheter des munitions", "Acheter une nouvelle monture", "Engager des hommes"],
    ["Boire un verre au saloon", "Aller à l'église", "Rendre visite au docteur"],
  ],
  artifacts: [
    { name: "Revolver Peacemaker", description: "Colt 45 à la crosse ornée. Il ne rate jamais sa cible à moins de 50 pas." },
    { name: "Chapeau du Vent", description: "Chapeau de cow-boy usé qui protège du soleil et des balles perdues." },
    { name: "Montre à Gousset", description: "Montre en or ayant appartenu à un hors-la-loi légendaire. Elle s'arrête à l'heure de sa mort." },
    { name: "Selle Apache", description: "Selle confortable et silencieuse. Le cheval ne se fatigue jamais avec elle." },
    { name: "Bouteille de Whisky", description: "Whisky vieux de 20 ans. Une gorgée soigne les blessures et donne du courage." },
    { name: "Carte de l'Ouest", description: "Carte ancienne marquée de symboles indiens. Elle mène à des sources cachées." },
    { name: "Bible du Prédicateur", description: "Ancienne bible contenant des cartes et des billets de banque dans ses pages creuses." },
    { name: "Fer à Cheval Chanceux", description: "Fer à cheval trouvé sur la piste. Porter chance à qui le possède." },
  ],
  monsters: [
    "un Coyote enragé à la taille anormale",
    "un Grizzly géant des montagnes",
    "un Puma traqueur silencieux",
    "un Serpent à sonnette mortel",
    "une Meute de loups affamés",
    "un Aigle royal carnivore",
    "un Taureau furieux échappé du ranch",
    "un Scorpion du désert géant",
    "un Vautour charognard agressif",
    "un Crocodile du fleuve Rouge",
  ],
};
